import drUmaPhoto from '../assets/AHT-Speaker-PIC/dr-uma.webp'
import shivaniPhoto from '../assets/AHT-Speaker-PIC/shivani-kulkarni.webp'
import ujjvalaPhoto from '../assets/AHT-Speaker-PIC/ujjvala-ballal.webp'
import snehaPhoto from '../assets/AHT-Speaker-PIC/sneha-bhonsle.webp'
import drBhaskarPhoto from '../assets/AHT-Speaker-PIC/dr-bhaskar.webp'
import drAjitPhoto from '../assets/AHT-Speaker-PIC/dr-ajit-audipudi.webp'
import darioPhoto from '../assets/AHT-Speaker-PIC/dario-heymann.webp'
import anirudhPhoto from '../assets/AHT-Speaker-PIC/anirudh-iyer.jpg'
import kirtiPhoto from '../assets/AHT-Speaker-PIC/kirti-yadav.jpg'
import saarthakPhoto from '../assets/AHT-Speaker-PIC/dr-saarthak-bakshi.jpg'
import anupPhoto from '../assets/AHT-Speaker-PIC/dr-anup-warrier.jpg'
import muthuPhoto from '../assets/AHT-Speaker-PIC/dr-muthu-dhandapani.jpg'
import smitaPhoto from '../assets/AHT-Speaker-PIC/smita-malipatil.jpg'
import drAmitRajPhoto from '../assets/AHT-Speaker-PIC/dr-amit-raj.webp'
import drAnandSivaramanPhoto from '../assets/AHT-Speaker-PIC/dr-anand-sivaraman.webp'
import drKaramveerPhoto from '../assets/AHT-Speaker-PIC/dr-karamveer-chhabra.webp'
import vivekRajagopalPhoto from '../assets/AHT-Speaker-PIC/vivek-rajagopal.webp'
import vsVenkateshPhoto from '../assets/AHT-Speaker-PIC/vs-venkatesh.webp'

const speakerRecords = [
  {
    id: 'speaker-shivani-kulkarni',
    name: 'Shivani Kulkarni',
    title: 'Vice President',
    organization: 'PrimeVP',
    tagline: 'Early Stage Tech VC — Fintech, Marketplaces & Consumer',
    biography:
      'Shivani Kulkarni is a venture capital investor focused on early-stage technology companies across Fintech, Marketplaces, and Consumer segments. As Vice President at PrimeVP, she has built a portfolio spanning financial infrastructure, embedded finance, and D2C brands. Prior to PrimeVP, she led venture investments at Flipkart where she backed companies including Finbox, Hyperface, GOAT Brand Labs, and Ninjacart. She started her career in Investment Banking at Avendus Capital. Shivani holds an MBA in Finance from XLRI Jamshedpur (Director\'s Merit List) and a Gold Medal in Electronics & Communication Engineering from PES University.',
    photoUrl: shivaniPhoto,
    linkedinUrl: 'https://www.linkedin.com/in/kulkarnishivani/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 1,
    expertise: ['Venture Capital', 'Fintech', 'Marketplaces', 'Consumer Tech', 'Early Stage Investing'],
    highlights: [
      { label: 'Current', value: 'Vice President, PrimeVP' },
      { label: 'Previously', value: 'Venture Investments, Flipkart' },
      { label: 'Portfolio', value: 'Finbox · Hyperface · GOAT Brand Labs · Ninjacart' },
      { label: 'Also Investing In', value: 'Elchemy · Navadhan Capital · Metafin' },
    ],
    education: [
      {
        degree: 'MBA, Finance',
        institution: 'XLRI Jamshedpur',
        year: '2018',
        achievement: "Director's Merit List",
      },
      {
        degree: 'B.E., Electronics & Communication Engineering',
        institution: 'PES University, Bangalore',
        year: '2016',
        achievement: 'Gold Medallist',
      },
    ],
    awards: [
      "Director's Merit List — XLRI Jamshedpur, 2017",
      'Gold Medal — PES University, 2016',
    ],
  },
  {
    id: 'speaker-dr-uma-nambiar',
    name: 'Dr. Uma Nambiar',
    title: 'CEO, IISc Medical School Foundation',
    organization: 'IISc Medical School Foundation',
    tagline: 'Neurosurgeon · Healthcare Administrator · Digital Health Pioneer',
    biography:
      'Dr. Uma Nambiar is a trained neurosurgeon and healthcare administrator with over forty years in the healthcare industry. An alumna of Armed Forces Medical College Pune, Sree Chitra Tirunal Institute Trivandrum, and Faculty of Management Studies Delhi, she has also trained at Beth Israel Hospital New York and Necker Enfant Malades Paris. She has worked across India and Africa as a Surgical Neuro-oncologist and in CXO roles at leading corporate hospitals. Dr. Nambiar has commissioned greenfield hospitals and re-engineered brownfield hospitals across multiple geographies, served as Special Technical Advisor to the Ministry of Health in Djibouti, and as a Digital Health consultant to a private hospital group in Botswana. She is an Independent Board Director for Hemas Hospital Group, Sri Lanka and IIHMR Bangalore, and an Honorary Professor at Jawaharlal Nehru Centre for Advanced Scientific Research.',
    photoUrl: drUmaPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 2,
    expertise: ['Neurosurgery', 'Digital Health', 'Healthcare Administration', 'Telemedicine', 'Hospital Commissioning'],
    highlights: [
      { label: 'Current', value: 'CEO, IISc Medical School Foundation' },
      { label: 'Co-Founder', value: 'DHIA — Digital Health India Association' },
      { label: 'Board Director', value: 'Hemas Hospital Group, Sri Lanka' },
      { label: 'Board Director', value: 'IIHMR, Bangalore' },
      { label: 'VP', value: 'Telemedicine Society of India' },
    ],
    education: [
      { degree: 'MBBS', institution: 'Armed Forces Medical College, Pune', year: '1982', achievement: '' },
      { degree: 'M.S. (General Surgery)', institution: 'Armed Forces Medical College, Pune', year: '1990', achievement: '' },
      { degree: 'M.Ch. (Neurosurgery)', institution: 'Sree Chitra Tirunal Institute, Trivandrum', year: '1993', achievement: '' },
      { degree: 'MBA, Healthcare Administration', institution: 'Faculty of Management Studies, Delhi University', year: '2005', achievement: '' },
      { degree: 'Visiting Fellowship — Vascular Neurosurgery', institution: 'Mayo Clinic, Minnesota', year: '1997', achievement: '' },
      { degree: 'Visiting Fellowship — Pediatric Neurosurgery', institution: 'Beth Israel Hospital, New York', year: '1998', achievement: '' },
    ],
    awards: [
      'Excellence in Digital Health Award — UAE Healthcare Leaders\' Summit, 2024',
      'Global Healthcare Digital Women Leadership of the Year — World Health Congress, 2021',
      'Top 50 Strategists in Healthcare to Follow — Medgate Today, 2021',
      'CXO Health Excellence Award — 7th CXO Digital Innovation Health Summit, 2022',
      'Winner, Commonwealth Digital Health Award in Nursing Informatics, 2017',
      'Innovator in Healthcare — Women Leadership and Innovation Award, 2013',
      'Country Development Marketplace Award — World Bank, 2004',
    ],
  },
  {
    id: 'speaker-ujjvala-ballal-shetty',
    name: 'Ujjvala Ballal Shetty',
    title: 'CEO',
    organization: 'Aveksha Hospitals',
    tagline: 'Healthcare Entrepreneur · Lawyer · Advocate for Accessible Care',
    biography:
      'Ujjvala Ballal Shetty is an entrepreneur, lawyer, and committed advocate for accessible healthcare. As CEO of Aveksha Multi-Specialty Hospitals — a growing hospital group in North Bangalore — she is dedicated to delivering world-class healthcare at an affordable cost. Aveksha currently operates a flagship 125-bed branch at MS Palya, serving the community for over 13 years, with a new branch in Yelahanka launching in July 2026. Ujjvala began her career with Inclusive Planet, a startup that successfully changed Indian copyright law to improve literary access for the visually impaired, before practising with a senior litigation lawyer in Bangalore and transitioning into healthcare leadership. She also co-hosts an ongoing online series on Medico-Legal Issues for doctors, alongside Dr. RK Mani and Dr. Shashi Kumar of Cloud Physician.',
    photoUrl: ujjvalaPhoto,
    photoPosition: 'center 18%',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 3,
    expertise: ['Healthcare Leadership', 'Hospital Operations', 'Medico-Legal', 'Entrepreneurship', 'Accessible Healthcare'],
    highlights: [
      { label: 'Current', value: 'CEO, Aveksha Multi-Specialty Hospitals' },
      { label: 'Hospitals', value: 'MS Palya (125 beds, 13+ yrs) · Yelahanka (launching Jul 2026)' },
      { label: 'Background', value: 'Law · Inclusive Planet · Litigation Practice' },
      { label: 'Series', value: 'Co-host, Medico-Legal Issues for Doctors' },
    ],
    education: [
      {
        degree: 'LLB (Law)',
        institution: 'ULC, Bangalore',
        year: '',
        achievement: 'Vice President, AIESEC India',
      },
    ],
    awards: [],
  },
  {
    id: 'speaker-sneha-bhonsle',
    name: 'Sneha Bhonsle',
    title: 'Founder',
    organization: 'Benevolent Legal',
    tagline: 'Healthcare and life sciences lawyer',
    biography:
      'Sneha Bhonsle is the Founder of Benevolent Legal and a healthcare and life sciences lawyer specializing in medical law, healthcare regulation, digital health, and data protection. She advises hospitals, healthcare professionals, and healthtech startups on regulatory, compliance, and medico-legal matters. With experience spanning healthcare, technology, and law, including a stint as Legal & Compliance Consultant at CARPL.ai, Sneha brings valuable insights into the evolving legal landscape of healthcare innovation.',
    photoUrl: snehaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 4,
    expertise: ['Medical Law', 'Healthcare Regulation', 'Digital Health', 'Data Protection', 'Medico-Legal'],
    highlights: [
      { label: 'Current', value: 'Founder, Benevolent Legal' },
      { label: 'Previously', value: 'Legal & Compliance Consultant, CARPL.ai' },
      { label: 'Specialisation', value: 'Medical Law · Healthcare Regulation · Digital Health · Data Protection' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-bhaskar-rajakumar',
    name: 'Dr Bhaskar Rajakumar',
    title: 'CEO, Centre of Excellence in Health Tech and Med Tech',
    organization: 'Govt of Karnataka',
    tagline: 'Evangelising med tech and health innovations, supporting AI driven solutions for Public Health, One Health and Climate Change.',
    biography:
      'A physician by academia, specialised in radiology with masters in business administration. With ~ 20 years across clinical, non-clinical and administrative fields, Dr Bhaskar\'s expertise spans across public health, healthcare administration, insurance, medical affairs, regulatory and pharmacovigilance, medical education, public policy, disaster management and healthcare innovation.\nHe is currently the CEO of Centre of Excellence in Health Tech and Med Tech, Govt of Karnataka and also serves as advisory for Bangalore Bio Innovation Centre, GoK and AI & Robotics Technology Park (ARTPARK), IISc. His present focus is on evangelising med tech and health innovations, supporting AI driven solutions for Public Health, One Health and Climate Change.\nHe is also Adjunct faculty at Rajiv Gandhi University of Medical Sciences, Karnataka and Post Graduate Institute of Medical Education and Research at Chandigarh, teaching healthcare informatics and related subjects.\nPrior to this he was working as the OSD to the Chief Commissioner, BBMP and was heading the Covid 19 Central War Room at BBMP.\nHis earlier startup \'Mediknit\' was focused on integration of future technologies in healthcare education, and worked with more than 1 million healthcare professionals across India, APAC, and USA. His work on healthcare and innovations have received multiple accolades and recognitions across the globe.\nHe has volunteered across the globe - including during the major disasters such as Tsunami in Tamil Nadu, Earth Quake in Nepal, Bomb blasts in Brussels etc.,\nPart of passion he is an avid runner with multiple marathons completed across the country and practices theatre.',
    photoUrl: drBhaskarPhoto,
    linkedinUrl: 'https://www.linkedin.com/in/drbhaskar/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 5,
    expertise: ['MedTech', 'HealthTech', 'Public Health', 'AI in Healthcare', 'Healthcare Innovation', 'Digital Health'],
    highlights: [
      { label: 'Current', value: 'CEO, Centre of Excellence in Health Tech and Med Tech, GoK' },
      { label: 'Advisory', value: 'Bangalore Bio Innovation Centre · ARTPARK, IISc' },
      { label: 'Faculty', value: 'RGUHS Karnataka · PGIMER Chandigarh' },
      { label: 'Founder', value: 'Mediknit — 1M+ healthcare professionals across India, APAC & USA' },
    ],
    education: [
      { degree: 'MBBS (Radiology specialisation)', institution: '', year: '', achievement: '' },
      { degree: 'MBA', institution: '', year: '', achievement: '' },
    ],
    awards: [
      'Top 100 Healthcare Leaders — Global Listing, 2018',
      'Top 50 Smart Health Leaders — Global, 2018',
      'Namma Bengaluru Healthcare Professional of the Year, 2021',
      'Deccan Herald Covid Warrior Award, 2022',
      'Covid Warrior Award — St Joseph\'s University, 2022',
      'Speaker at multiple national and international conferences',
    ],
  },
  {
    id: 'speaker-dr-ajit-audipudi',
    name: 'Dr. Ajit Audipudi',
    title: 'General Surgeon & Healthcare AI Strategist',
    organization: 'SVS Medical College & Hospital | AdaptAI Health Tech',
    tagline: 'Helping healthcare organizations move from AI curiosity to AI adoption.',
    biography:
      'Dr. Ajit Audipudi is a General Surgeon, Healthcare AI Strategist, and Director of the AI Research Wing at SVS Medical College & Hospital, India. He is also Co-Founder of AdaptAI Health Tech, where he focuses on the practical implementation of artificial intelligence in healthcare.\nHis work centers on helping healthcare organizations move from AI curiosity to AI adoption through clinical workflow integration, healthcare AI strategy, research systems, and implementation frameworks. He is involved in developing AI-enabled healthcare solutions, clinical data registries, and research initiatives that support evidence generation, quality improvement, and digital transformation in healthcare.\nDr. Audipudi works at the intersection of medicine, healthcare research, and emerging technologies, with a particular interest in translating AI from proof-of-concept into real-world clinical practice. He has served as a speaker, subject matter expert, and workshop lead on artificial intelligence in healthcare for clinicians, healthcare professionals, and academic audiences.',
    photoUrl: drAjitPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 6,
    expertise: ['Healthcare AI', 'Clinical AI Implementation', 'AI Strategy', 'General Surgery', 'Digital Health Transformation'],
    highlights: [
      { label: 'Director', value: 'AI Research Wing, SVS Medical College & Hospital' },
      { label: 'Co-Founder', value: 'AdaptAI Health Tech Pvt Ltd' },
      { label: 'Focus', value: 'Translating AI from proof-of-concept to real-world clinical practice' },
      { label: 'Engagements', value: 'Speaker, subject matter expert & workshop lead on AI in healthcare' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-anirudh-iyer',
    name: 'Anirudh Iyer',
    title: 'Vice President, Investments',
    organization: 'Xeed Ventures',
    tagline: 'Partnering with early-stage founders to build scalable businesses',
    biography:
      'Anirudh Iyer is Vice President for Investments at Xeed Ventures, where he partners with early-stage founders building tech-first and tech-enabled businesses from their first conviction cheque through scale. He focuses on sourcing and evaluating investments, working closely with portfolio companies, and developing strategic frameworks that help founders navigate growth.\nAt Xeed Ventures, Anirudh has worked with startups across SaaS, AI, fintech, enterprise technology, and consumer technology.\nAs an early-stage investor, Anirudh works closely with founders on investment readiness, business strategy, fundraising, and scaling technology businesses. His interests span emerging technologies, venture investing, and helping entrepreneurs build category-defining companies from inception to growth.\nAnirudh is also a CAIA (Chartered Alternative Investment Analyst) Charterholder, reflecting his expertise in alternative investments, venture capital, private equity, and portfolio management.',
    photoUrl: anirudhPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 8,
    expertise: ['Venture Capital', 'Early Stage Investing', 'SaaS', 'AI', 'Fintech', 'Alternative Investments'],
    highlights: [
      { label: 'Current', value: 'Vice President, Investments — Xeed Ventures' },
      { label: 'Focus', value: 'Tech-first & tech-enabled early-stage startups' },
      { label: 'Sectors', value: 'SaaS · AI · Fintech · Enterprise Tech · Consumer Tech' },
      { label: 'Credential', value: 'CAIA Charterholder — Chartered Alternative Investment Analyst' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-kirti-yadav',
    name: 'Kirti Yadav',
    title: 'Head, Integrated Marketing & SBU Head, Rehabilitation',
    organization: 'MAIINS, Marengo Asia Hospitals',
    tagline: 'Healthcare Growth Strategist | AI-Driven Marketing & Rehabilitation Leader',
    biography:
      'Kirti Yadav is a healthcare business leader with over 16 years of experience spanning healthcare marketing, business development, rehabilitation, home healthcare, and digital health. She currently leads Integrated Marketing and the Rehabilitation Business Unit at MAIINS (Marengo Asia Institute of Neurosciences & Spine), one of India\'s leading neuroscience institutes under Marengo Asia Hospitals, Gurugram.\nWith a unique blend of clinical expertise as a physiotherapist and commercial leadership experience, Kirti has successfully built and scaled healthcare businesses, developed high-performing teams, and driven sustainable growth across hospitals, rehabilitation services, and home healthcare organizations.\nHer expertise lies in healthcare growth strategy, AI-driven patient engagement, integrated marketing, brand building, referral network development, and business transformation. She has played a pivotal role in positioning MAIINS as a leading destination for neuroscience and rehabilitation care through innovative marketing, digital transformation, and stakeholder engagement initiatives.\nKirti is passionate about leveraging technology and artificial intelligence to enhance patient experiences, improve healthcare accessibility, and create scalable growth models for healthcare organizations.',
    photoUrl: kirtiPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 9,
    expertise: ['AI in Healthcare Marketing', 'Digital Transformation in Healthcare', 'Patient Acquisition & Engagement', 'Healthcare Brand Strategy', 'Rehabilitation & Allied Health', 'Business Growth & Revenue Expansion'],
    highlights: [
      { label: 'Current', value: 'Head, Integrated Marketing & SBU Head Rehabilitation — MAIINS, Marengo Asia Hospitals' },
      { label: 'Experience', value: '16+ years in healthcare marketing, business development & rehabilitation' },
      { label: 'Background', value: 'Physiotherapist with commercial leadership expertise' },
      { label: 'Focus', value: 'AI-driven patient engagement · Brand building · Referral network development' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-dario-heymann',
    name: 'Dr. Dario Heymann',
    title: 'Co-founder & Chief Data & Technology Officer',
    organization: 'Galen Growth',
    tagline: "Building the world's leading digital health intelligence platform.",
    biography:
      "Dario co-founded Galen Growth during his PhD, where he serves as Chief Data & Technology Officer. He led the development of HealthTech Alpha, the world's foremost digital health venture intelligence platform. HealthTech Alpha tracks over 70,000 companies and close to two billion data points, enabling AI-powered insights that guide health systems and corporations globally in shaping their digital health strategies.\nUnder Dario's leadership, Galen Growth achieved profitability from its first year and executed over 150 strategic projects for multinational pharmaceutical, insurance, and medical device companies, as well as government organizations.\nDario also advises the Singapore Eye Research Institute and the SingHealth AI Office, focusing on developing AI-powered operational and clinical solutions, with particular focus on the sovereign AI space.\nHe led the commercialisation of Enigma Health in early 2025, which was merged with a US business in 2026.\nPrior to SingHealth and Galen Growth, Dario worked in both academia and pharma in Singapore, China and Germany. He holds a PhD in Material Sciences, specialising in structural biology, as well as master's degrees in Material Sciences, Biochemistry and Molecular Biology.",
    photoUrl: darioPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 7,
    expertise: ['Digital Health Intelligence', 'HealthTech Strategy', 'AI in Healthcare', 'Sovereign AI', 'Venture Intelligence'],
    highlights: [
      { label: 'Platform', value: 'HealthTech Alpha — 70,000+ companies, ~2B data points' },
      { label: 'Advisory', value: 'Singapore Eye Research Institute · SingHealth AI Office' },
      { label: 'Track Record', value: '150+ strategy projects for pharma, insurers, medtech & governments' },
      { label: 'Special Advisor', value: 'Governments on AI & GenAI integration in healthcare' },
    ],
    education: [
      { degree: 'PhD, Material Sciences (Structural Biology)', institution: '', year: '', achievement: '' },
      { degree: "MSc, Material Sciences", institution: '', year: '', achievement: '' },
      { degree: 'MSc, Biochemistry & Molecular Biology', institution: '', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-anup-warrier',
    name: 'Dr. Anup R. Warrier',
    title: 'Group Chief of Medical Services & Quality',
    organization: 'Aster DM Healthcare',
    tagline: 'Driving clinical excellence, quality & digital transformation across an 18-hospital network.',
    biography:
      'Dr. Anup R. Warrier is Group Chief of Medical Services & Quality at Aster DM Healthcare, where he leads clinical strategy, quality, patient safety, and digital transformation across an 18-hospital network. A physician executive with nearly two decades of experience, his career spans infectious diseases, healthcare quality, clinical governance, accreditation, and enterprise healthcare leadership.\nOver the years, Dr. Warrier has led large-scale initiatives in quality improvement, EMR implementation, AI adoption, greenfield hospital commissioning, and clinical governance — driving measurable improvements in patient safety and healthcare outcomes. He reduced composite HAI rates from 2.0% to 0.9% group-wide, sustained six JCI accreditation cycles, and delivered award-winning reductions in CLABSI and surgical-site infections.\nBeyond his leadership at Aster, he serves in national and international roles focused on infection prevention, antimicrobial stewardship, and healthcare quality, and has contributed extensively to clinical research, policy, and medical education with 30+ peer-reviewed publications.',
    photoUrl: anupPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 11,
    expertise: ['Clinical Governance & Patient Safety', 'Quality Systems (JCI · NABH · ACHSI)', 'Infectious Diseases & Antimicrobial Stewardship', 'EMR & AI / Digital Adoption', 'Greenfield Hospital Commissioning', 'M&A Clinical Due Diligence'],
    highlights: [
      { label: 'Current', value: 'Group Chief of Medical Services & Quality — Aster DM Healthcare (18 hospitals)' },
      { label: 'Impact', value: 'Reduced composite HAI rates from 2.0% → 0.9% group-wide; sustained 6 JCI accreditation cycles' },
      { label: 'External Roles', value: 'Chairperson, CAHO IPC Forum · Faculty, WHO Infection Prevention programmes · Kerala AMR Committee' },
      { label: 'Research', value: '30+ peer-reviewed publications — antimicrobial resistance, infection prevention, sepsis & implementation science' },
    ],
    education: [
      { degree: 'INSEAD — Leadership Programme for Senior Executives (ILPSE)', institution: '', year: 'Ongoing', achievement: '' },
      { degree: 'Harvard Medical School — AI in Healthcare', institution: '', year: 'Ongoing', achievement: '' },
      { degree: 'DNB, General Medicine', institution: '', year: '', achievement: '' },
      { degree: 'MBBS', institution: 'Government Medical College, Trivandrum', year: '', achievement: '' },
    ],
    awards: [
      'SHEA International Ambassador Award',
      'Healthcare Management Asia Award 2016',
      'Healthcare Management Asia Award 2019',
      'SHEA International Research Grant',
      'IDSA Centre of Excellence Recognition',
      'ESCMID European Centre for Collaboration Recognition',
    ],
  },
  {
    id: 'speaker-smita-malipatil',
    name: 'Smita Malipatil',
    title: 'Founder & CEO',
    organization: 'Hosa Health',
    tagline: 'Building a pediatric intelligence layer for Gen Alpha Healthcare.',
    biography:
      'Smita Malipatil is the Founder & CEO of Hosa Health, building a pediatric intelligence layer for Gen Alpha Healthcare.\nSmita began her entrepreneurial journey as the founder of Kieon, one of the UK\'s pioneering digital transformation agencies. Under her leadership, Kieon expanded its operations across the UK, US, and India — culminating in a successful exit to a major UK PLC. Post her exit, she was CEO for two companies in the Deeptech and AI/ML sectors, where she successfully scaled the organizations and led them through key stages of growth.\nAn alumna of Harvard Business School, Smita is a passionate advocate for entrepreneurship and women in leadership. She is an angel investor and startup mentor, and serves as a Founding Member of the India-UK Responsible AI Group, a committee member of the Start-up Vision Group Karnataka, and Board and Charter Member at TiE Bangalore.',
    photoUrl: smitaPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/bigchief/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 13,
    expertise: ['Pediatric Digital Health', 'AI/ML & Deeptech', 'Digital Transformation', 'Entrepreneurship & Exits', 'Angel Investing', 'Responsible AI'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO — Hosa Health (pediatric intelligence layer for Gen Alpha)' },
      { label: 'Previous', value: 'Founder, Kieon — UK digital transformation agency; successful exit to major UK PLC' },
      { label: 'Leadership', value: 'CEO at two Deeptech & AI/ML companies post-exit; scaled through key growth stages' },
      { label: 'Community', value: 'Founding Member, India-UK Responsible AI Group · TiE Bangalore Board & Charter Member' },
    ],
    education: [
      { degree: 'Harvard Business School', institution: '', year: '', achievement: 'Alumna' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-muthu-dhandapani',
    name: 'Dr. Muthu Dhandapani',
    title: 'Vice President — Quality & Regulatory Compliance',
    organization: 'Tricog Health',
    tagline: 'Bridging innovation, regulation & commercialization across medical devices & AI-powered digital health.',
    biography:
      'Dr. Dhandapani is a strategic and execution-driven leader with 22 years of regulatory experience across India, USA, and EU — building and scaling medical device, diagnostics, and digital health functions. He has proven success in leading product development, R&D and manufacturing facility setup, regulatory affairs, quality systems, multicentric clinical studies, AI/ML-based SaMD (Software as a Medical Device), and cloud-connected medical platforms.\nHe brings strong command over global regulations including CDSCO, FDA, ISO 13485, IEC 62304, MDSAP, EU IVDR, and MDR, with deep leadership experience in new product development, clinical validation, software lifecycle management, and international market access.\nBeyond his industry role, Dr. Dhandapani serves as a mentor on the board of 12 bio-incubators and TBIs including BBC, C-CAMP, ISB, MS Ramaiah, JSS Mysuru, STPI, IIT Guwahati, Yenepoya, and GINSERV.',
    photoUrl: muthuPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 12,
    expertise: ['Medical Device Regulation (CDSCO · FDA · EU MDR)', 'AI/ML SaMD & Digital Health', 'Quality Systems (ISO 13485 · MDSAP)', 'Clinical Validation & Studies', 'R&D & Manufacturing Setup', 'Startup Mentorship & Incubation'],
    highlights: [
      { label: 'Current', value: 'VP, Quality & Regulatory Compliance — Tricog Health' },
      { label: 'Experience', value: '22 years across India, USA & EU in medical devices, diagnostics & digital health' },
      { label: 'Expertise', value: 'AI/ML SaMD · Cloud-connected medical platforms · International market access · MDSAP · EU IVDR' },
      { label: 'Mentorship', value: 'Board mentor at 12 bio-incubators & TBIs — BBC, C-CAMP, ISB, IIT Guwahati, STPI & more' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-amit-raj',
    name: 'Dr. Amit Raj',
    title: 'Founder & CEO, Plexus AI | Cardiologist',
    organization: 'Plexus AI / Plexus Medcare Hospital',
    tagline: 'Building clinical AI infrastructure that makes AI safe, trusted and deployable at bedside.',
    biography:
      'Dr. Amit Raj is a cardiologist, hospital leader, and healthcare entrepreneur dedicated to bridging the gap between healthcare AI innovation and real-world clinical adoption.\nAs Founder & CEO of Plexus AI and Managing Director of Plexus Medcare Hospital, he is building infrastructure that connects clinical practice with AI innovation. Through Plexus AI\'s hospital-based platform, he enables AI startups, hospitals, and healthcare organizations to navigate three critical stages: Validation → Deployment → Market Access.\nThis framework ensures AI solutions are clinically validated, responsibly governed, and scaled through real-world evidence and physician-led implementation. His work focuses on making AI safe, practical, and scalable within everyday clinical workflows — not confined to laboratories or theoretical environments.\nHe believes the future of healthcare will be defined not only by smarter algorithms, but by the ability to responsibly integrate AI into patient care. His vision is to position India as a global leader in trusted clinical AI validation, deployment, and innovation, improving healthcare outcomes through safe and evidence-driven adoption.',
    photoUrl: drAmitRajPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/doctoramitraj',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 14,
    expertise: ['Clinical AI Validation', 'Real-World Evidence', 'Hospital AI Deployment', 'Responsible AI Governance', 'Cardiovascular AI', 'Digital Health Strategy'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO, Plexus AI' },
      { label: 'Also', value: 'Managing Director, Plexus Medcare Hospital' },
      { label: 'Framework', value: 'Clinical AI Validation → Deployment → Market Access' },
      { label: 'Mission', value: 'Positioning India as a global leader in trusted clinical AI' },
    ],
    education: [
      { degree: 'Executive Education', institution: 'Harvard Business School', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'IIM Ahmedabad', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'ISB', year: '', achievement: '' },
    ],
    awards: [
      'ESC | ACC | EAPCI | EBAC Member',
    ],
  },
  {
    id: 'speaker-dr-anand-sivaraman',
    name: 'Dr. Anand Sivaraman',
    title: 'Founder & CEO',
    organization: 'Remidio',
    tagline: 'Reimagining healthcare access through AI-powered medical devices.',
    biography:
      'Dr. Anand Sivaraman is redefining the way healthcare innovation reaches those who need it most, through Remidio — an India-headquartered, AI-enabled medical devices company that has pioneered innovations delivering specialist care to primary care, public health centers, and patient homes, starting with Ophthalmic Care.\nA scientist, entrepreneur, and problem-solver, he earned his Master\'s, PhD and Postdoctoral degrees at MIT, followed by 20 years of experience building novel products out of India in in-vitro diagnostics and optical imaging.\nAnand believes that, in order to create disruptive healthcare access, product innovations need to be combined with both delivery and business model innovations. Traditional medical devices often remain too expensive, complex, and designed for specialists — not keeping the healthcare worker at the last mile in mind. Remidio\'s innovations challenge this model, bringing world-class diagnostics to the last mile with simplicity, efficiency, and affordability.\nHis approach is rooted in a vision for equitable healthcare, where groundbreaking technology is not just developed for the privileged few but designed to work in the real-world conditions of both developing and developed nations. His greatest strength is his ability to turn constraints into catalysts for innovation — seeing challenges like limited infrastructure, affordability gaps, or workforce shortages as opportunities to design smarter, more scalable healthcare solutions.',
    photoUrl: drAnandSivaramanPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 15,
    expertise: ['AI-Powered Medical Devices', 'Ophthalmic Diagnostics', 'Last-Mile Healthcare', 'Medical Innovation', 'Equitable Healthcare Access', 'Optical Imaging'],
    highlights: [
      { label: 'Current', value: 'CEO & Founder, Remidio' },
      { label: 'Focus', value: 'AI-enabled devices bringing specialist care to primary care & patient homes' },
      { label: 'Background', value: '20+ years building novel diagnostics & optical imaging products from India' },
      { label: 'Vision', value: 'Equitable healthcare — world-class diagnostics at the last mile' },
    ],
    education: [
      { degree: 'Postdoctoral Research', institution: 'MIT', year: '', achievement: '' },
      { degree: 'PhD', institution: 'MIT', year: '', achievement: '' },
      { degree: "Master's", institution: 'MIT', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-saarthak-bakshi',
    name: 'Dr. Saarthak Bakshi',
    title: 'Founder & CEO',
    organization: 'Risaa IVF and NEOS Angels',
    tagline: 'Combining healthcare innovation with entrepreneurship to advance fertility care and support the next generation of healthcare startups.',
    biography:
      'Dr. Saarthak Bakshi is the Founder & CEO of RISAA IVF and NEOS Angels, where he combines healthcare innovation with entrepreneurship to advance fertility care and support the next generation of healthcare startups. A serial entrepreneur, investor, and startup mentor, he has guided more than 35 startups while building ventures focused on healthcare, education, and social impact.\nBeyond his entrepreneurial journey, Dr. Bakshi actively contributes to India\'s innovation ecosystem through leadership and advisory roles across healthcare, startup incubators, and industry organizations. His work is driven by a commitment to improving healthcare accessibility, promoting fertility awareness, and enabling innovation through collaboration, mentorship, and investment.',
    photoUrl: saarthakPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/saarthakbakshi/',
    twitterUrl: 'https://x.com/saarthak_bakshi',
    isFeatured: true,
    displayOrder: 10,
    expertise: ['Fertility & IVF', 'Healthcare Innovation', 'Startup Mentorship', 'Venture Investing', 'Social Impact', 'Healthcare Entrepreneurship'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO — RISAA IVF and NEOS Angels' },
      { label: 'Impact', value: 'Mentored & guided 35+ startups across healthcare, education & social impact' },
      { label: 'Roles', value: 'Director, HealthPod Incubator · President, Voice of Healthcare · Founder, IIRFT' },
      { label: 'Mission', value: 'Improving healthcare accessibility · Fertility awareness · Innovation through mentorship' },
      { label: 'Leadership', value: 'AIMA YLC National Brand Communication Chair · CRM Academy of Asia Board of Directors' },
      { label: 'Advisory', value: 'Strategic Advisor & Board Member — INY Foundation · Trustee, Foundation of Healthcare Wellness & Promotion' },
      { label: 'Councils', value: 'Indo-German Young Leaders Forum · CII Young Indians Core Executive Committee · Startup Leadership Program Leader' },
    ],
    education: [],
    awards: [
      '50 Under 50 Healthcare Entrepreneur of the Year 2025',
      'Best Healthcare Entrepreneur of the Year 2025',
      '100 Most Impactful Healthcare Leaders 2024 — World Health & Congress Awards',
      'AIMA Young Leaders Award 2024',
      'Entrepreneur of the Year in Healthcare 2023 & 2024 — Entrepreneur Magazine',
      'National Award in Healthcare — Delhi Management Association 2023',
      'IVF Chain of the Year 2023–25',
      'Best of the Best IVF India Award 2023–24',
      'Best Infertility Clinic India 2023 — Times of India',
      'CSC\'23 Fellow — The Duke of Edinburgh\'s Commonwealth Study Conference, Canada',
      'FORBES 30 Under 30 Asia',
      'BW Healthcare World 40 Under 40',
      'Entrepreneur 35 Under 35',
      'Multiple TEDx Speaker',
    ],
  },
  {
    id: 'speaker-dr-karamveer-chhabra',
    name: 'Dr. Karamveer S. Chhabra',
    title: 'Executive Director',
    organization: 'Alive Wellness Clinics',
    tagline: 'Driving innovation in aesthetic medicine, wellness & patient-centric care',
    biography:
      'Dr. Karamveer S. Chhabra is an Indian aesthetic physician, entrepreneur, and healthcare leader who has emerged as one of the prominent young voices in aesthetic medicine and wellness in India. He currently serves as Executive Director of Alive Wellness Clinics, one of India\'s leading chains in clinical dermatology and aesthetic medicine, with a growing network of clinics across the country.\nWith a unique combination of medical understanding, business strategy, and global exposure, Dr. Chhabra has played a key role in expanding the organization\'s footprint, strengthening its digital ecosystem, and positioning the group among India\'s fast-growing dermatology and aesthetic healthcare brands. Since being appointed Executive Director in 2023, he has contributed significantly to operational expansion, patient experience optimization, and the integration of advanced aesthetic technologies and treatment verticals.\nA graduate of M. S. Ramaiah Medical College, Dr. Chhabra combines evidence-based medicine with a modern understanding of aesthetics, wellness, regenerative medicine, and patient-centric care. His work spans injectables, body contouring, regenerative aesthetics, practice development, and the growing intersection of medicine, technology, and consumer healthcare.\nHe is also the Founder of Alive Institute of Aesthetics, a leading training platform focused on aesthetic medicine education, which has trained 200+ doctors and 400+ support staff in about three years, with collaborative programs alongside globally recognized brands including APTOS and Merz Aesthetics. Dr. Chhabra has been recognized by The Times of India for his contributions to aesthetic medicine, healthcare entrepreneurship, and clinical management.',
    photoUrl: drKaramveerPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 16,
    expertise: ['Aesthetic Medicine', 'Regenerative Aesthetics', 'Healthcare Entrepreneurship', 'Practice Development', 'Wellness & Patient Care'],
    highlights: [
      { label: 'Current', value: 'Executive Director, Alive Wellness Clinics' },
      { label: 'Founder', value: 'Alive Institute of Aesthetics' },
      { label: 'Committee', value: 'Core Committee Member, Association of Aesthetic Doctors of India (AADi)' },
      { label: 'Training Impact', value: '200+ doctors & 400+ support staff trained in ~3 years' },
      { label: 'Recognition', value: 'Recognized by The Times of India for aesthetic medicine & healthcare leadership' },
      { label: 'International', value: 'Faculty speaker — IMCAS World Congress, AMWC, MAIS Summit (Spain)' },
    ],
    education: [
      { degree: 'MBBS', institution: 'M. S. Ramaiah Medical College', year: '', achievement: '' },
    ],
    awards: [
      'Recognized by The Times of India for achievements in aesthetic medicine & healthcare entrepreneurship',
    ],
  },
  {
    id: 'speaker-vivek-rajagopal',
    name: 'Vivek Rajagopal',
    title: 'Group Chief Analytics & AI Officer',
    organization: 'Narayana Health',
    tagline: 'Leading AI-driven clinical & operational transformation that delivers better care and outcomes',
    biography:
      'Vivek Rajagopal is the Group Chief Analytics & AI Officer at Narayana Health, one of India\'s largest hospital chains. Over the past 15 years, he has not only led but also founded the organisation\'s Analytics & AI division — Medha AI, building it into a central driver of transformation, advancing clinical care, optimising operations, enhancing patient engagement, and strengthening financial outcomes. He combines this deep industry experience with a PGDM from the prestigious Indian Institute of Management Bangalore (IIMB).',
    photoUrl: vivekRajagopalPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 17,
    expertise: ['Healthcare Analytics', 'Artificial Intelligence', 'Clinical Transformation', 'Operations Optimization', 'Patient Engagement'],
    highlights: [
      { label: 'Current', value: 'Group Chief Analytics & AI Officer, Narayana Health' },
      { label: 'Founder', value: 'Medha AI — Narayana Health\'s Analytics & AI division' },
      { label: 'Experience', value: '15+ years leading AI-driven clinical & operational transformation' },
      { label: 'Focus', value: 'Clinical care · Operations · Patient engagement · Financial outcomes' },
    ],
    education: [
      { degree: 'PGDM', institution: 'Indian Institute of Management, Bangalore (IIMB)', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-vs-venkatesh',
    name: 'V.S. Venkatesh',
    title: 'Managing Director',
    organization: 'Zentor Medtech Pvt Ltd',
    tagline: 'Transforming healthcare businesses through strategy, leadership & innovation',
    biography:
      'Venkatesh is a seasoned business consultant and startup mentor with over three decades of experience in the global healthcare sector. His expertise spans 360 degrees across pharmaceuticals, hospitals, diagnostics, and health tech & medtech, with a proven track record of steering organizations toward sustainable growth and excellence.\nAs a strategic leader, he has held C-level positions with renowned brands, including Apollo Hospitals, SRL Ranbaxy, Zydus Cadila, Bourn Hall (UK), and JDC (UAE).\nTrained at leading institutions like IIM-Ahmedabad, Harvard Business School, and Wharton, Venkatesh provides advisory services and mentorship to first-generation entrepreneurs and established businesses seeking professionalization or strategic turnarounds. He was also instrumental in taking GST successfully into the IPO. His unique approach combines critical business tactics with a deep understanding of organizational culture, focusing on the creative and expressive dimensions of leadership.\nA keynote speaker, Venkatesh has addressed audiences in over 15 countries on topics ranging from healthcare technology and management change to medical tourism. He has received numerous awards for his leadership and public speaking, including "CEO of the Year" (Dubai, 2017) and "Best International Speaker" (India, 2016).',
    photoUrl: vsVenkateshPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 18,
    expertise: ['Healthcare Strategy', 'Business Consulting', 'Startup Mentorship', 'Pharma & Medtech', 'Organizational Leadership'],
    highlights: [
      { label: 'Current', value: 'Managing Director, Zentor Medtech Pvt Ltd' },
      { label: 'Previously', value: 'C-level roles — Apollo Hospitals · SRL Ranbaxy · Zydus Cadila · Bourn Hall (UK) · JDC (UAE)' },
      { label: 'Experience', value: '30+ years across pharmaceuticals, hospitals, diagnostics & medtech' },
      { label: 'Speaking', value: 'Keynote speaker in 15+ countries on healthcare tech, management change & medical tourism' },
    ],
    education: [
      { degree: 'Executive Education', institution: 'IIM Ahmedabad', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'Harvard Business School', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'Wharton School', year: '', achievement: '' },
    ],
    awards: [
      'CEO of the Year — Dubai, 2017',
      'Best International Speaker — India, 2016',
    ],
  },
]

const agendaRecords = [
  {
    id: 'session-registration',
    displayOrder: 1,
    title: 'Registration & Welcome Tea',
    startTime: '2026-07-27T09:45:00+05:30',
    endTime: '2026-07-27T10:30:00+05:30',
    track: null,
    type: 'registration',
    description: 'Arrive, collect your event badge, enjoy refreshments, and connect with fellow attendees before the sessions begin.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-opening',
    displayOrder: 2,
    title: 'Welcome & Opening Remarks',
    startTime: '2026-07-27T11:00:00+05:30',
    endTime: '2026-07-27T11:20:00+05:30',
    track: null,
    type: 'emcee',
    description: 'Setting the stage for a day focused on healthcare innovation, technology adoption, and the future of care delivery.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-keynote-1',
    displayOrder: 3,
    title: 'Keynote Address',
    startTime: '2026-07-27T11:20:00+05:30',
    endTime: '2026-07-27T11:40:00+05:30',
    track: 'Keynote',
    type: 'keynote',
    description: 'A vision for the next decade of healthcare transformation.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-keynote-2',
    displayOrder: 4,
    title: 'Keynote Address',
    startTime: '2026-07-27T11:40:00+05:30',
    endTime: '2026-07-27T11:55:00+05:30',
    track: 'Keynote',
    type: 'keynote',
    description: 'Exploring emerging opportunities at the intersection of healthcare, technology, and innovation.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-1',
    displayOrder: 5,
    title: 'Panel: Hospitals & HealthTech',
    startTime: '2026-07-27T12:00:00+05:30',
    endTime: '2026-07-27T12:30:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'How hospitals and technology companies can work together to improve patient outcomes, operational efficiency, and digital transformation.',
    speakerId: null,
    speakers: [
      { name: 'Dr. Ujjwala' },
      { name: 'Dr. Karamveer S Chhabra' },
      { name: 'Dr. Amit Raaj' },
    ],
  },
  {
    id: 'session-fireside',
    displayOrder: 6,
    title: 'Fireside Chat',
    startTime: '2026-07-27T12:35:00+05:30',
    endTime: '2026-07-27T12:50:00+05:30',
    track: 'Fireside',
    type: 'fireside',
    description: 'An intimate conversation with a healthcare leader on the opportunities and challenges shaping the industry.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-sponsor-1',
    displayOrder: 7,
    title: 'Partner Spotlight',
    startTime: '2026-07-27T13:00:00+05:30',
    endTime: '2026-07-27T13:20:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare.',
    speakerId: null,
    speakers: [{ name: 'Sanket Shah' }],
  },
  {
    id: 'session-lunch',
    displayOrder: 8,
    title: 'Lunch Break',
    startTime: '2026-07-27T13:20:00+05:30',
    endTime: '2026-07-27T13:40:00+05:30',
    track: null,
    type: 'break',
    description: 'Enjoy lunch connecting with founders, healthcare leaders, investors, clinicians, and innovators.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-2',
    displayOrder: 9,
    title: 'Panel: The HealthTech Founder Journey',
    startTime: '2026-07-27T13:40:00+05:30',
    endTime: '2026-07-27T14:00:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'Building, scaling, and navigating the realities of creating healthcare startups.',
    speakerId: null,
    speakers: [
      { name: 'Hosa Health' },
      { name: 'Rimidio' },
      { name: 'Prodoc' },
    ],
  },
  {
    id: 'session-pitch',
    displayOrder: 10,
    title: 'The 3-Minute Pitch — Live Engagement',
    startTime: '2026-07-27T14:00:00+05:30',
    endTime: '2026-07-27T15:00:00+05:30',
    track: 'Interactive',
    type: 'interactive',
    description: 'Selected startups showcase their innovations before an audience of healthcare leaders, investors, and ecosystem stakeholders.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-3',
    displayOrder: 11,
    title: 'Panel: The VC Perspective',
    startTime: '2026-07-27T15:00:00+05:30',
    endTime: '2026-07-27T15:30:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'What investors are looking for in healthcare and healthtech today, and where the next opportunities lie.',
    speakerId: null,
    speakers: [
      { name: 'Ashima', organization: 'Sorin' },
      { name: 'Anirudh Iyer', organization: 'Xceed' },
      { name: 'Shivani Kulkarni', organization: 'PrimeVP' },
    ],
  },
  {
    id: 'session-hi-tea',
    displayOrder: 12,
    title: 'Networking Break',
    startTime: '2026-07-27T15:30:00+05:30',
    endTime: '2026-07-27T15:45:00+05:30',
    track: null,
    type: 'break',
    description: 'Refreshments and conversations.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-4',
    displayOrder: 13,
    title: 'Panel: Regulation, Compliance & the Law',
    startTime: '2026-07-27T15:50:00+05:30',
    endTime: '2026-07-27T16:10:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'Navigating policy, regulation, data governance, and legal considerations in healthcare innovation.',
    speakerId: null,
    speakers: [
      { name: 'Sneha Bhonsle' },
    ],
  },
  {
    id: 'session-sponsor-2',
    displayOrder: 14,
    title: 'Partner Spotlight',
    startTime: '2026-07-27T16:10:00+05:30',
    endTime: '2026-07-27T16:30:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Industry perspectives on enabling the future of healthcare.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-5',
    displayOrder: 15,
    title: 'Panel: AI in Healthcare Marketing',
    startTime: '2026-07-27T16:35:00+05:30',
    endTime: '2026-07-27T17:00:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'How AI is reshaping patient engagement, communication, growth, and healthcare brand building.',
    speakerId: null,
    speakers: [
      { name: 'Samir Karpe' },
      { name: 'Kriti Yadav' },
      { name: 'Rahul Jain' },
    ],
  },
  {
    id: 'session-sponsor-3',
    displayOrder: 16,
    title: 'Partner Spotlight',
    startTime: '2026-07-27T17:00:00+05:30',
    endTime: '2026-07-27T17:20:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Showcasing solutions and innovations powering the healthcare ecosystem.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-networking',
    displayOrder: 17,
    title: 'Networking & Booth Exploration',
    startTime: '2026-07-27T17:30:00+05:30',
    endTime: '2026-07-27T18:10:00+05:30',
    track: null,
    type: 'networking',
    description: 'Meet exhibitors, discover new solutions, and continue conversations with fellow attendees.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-gala',
    displayOrder: 18,
    title: 'Gala Dinner',
    startTime: '2026-07-27T18:30:00+05:30',
    endTime: '2026-07-27T21:30:00+05:30',
    track: null,
    type: 'gala',
    description: 'Wrap up the day with an evening of great conversations, new connections, and meaningful networking.',
    speakerId: null,
    speakers: [],
  },
]

function sortByDisplayOrder(items) {
  return items.slice().sort((a, b) => a.displayOrder - b.displayOrder)
}

function buildSpeakerMap(speakers) {
  return new Map(speakers.map((speaker) => [speaker.id, speaker]))
}

function attachSpeakersToAgenda(agendaItems, speakerMap) {
  return sortByDisplayOrder(agendaItems).map((item) => ({
    ...item,
    speaker: item.speakerId ? speakerMap.get(item.speakerId) ?? null : null,
    speakers: (item.speakers || []).map((s) => {
      if (!s.speakerId) return s
      const record = speakerMap.get(s.speakerId)
      return record ? { ...s, photoUrl: record.photoUrl, title: record.title } : s
    }),
  }))
}

function attachSessionsToSpeakers(speakers, agendaItems) {
  const sessionsBySpeakerId = new Map()
  for (const item of agendaItems) {
    const addSession = (id) => {
      if (!sessionsBySpeakerId.has(id)) sessionsBySpeakerId.set(id, [])
      const list = sessionsBySpeakerId.get(id)
      if (!list.some((i) => i.id === item.id)) list.push(item)
    }
    if (item.speakerId) addSession(item.speakerId)
    for (const s of item.speakers ?? []) {
      if (s.speakerId) addSession(s.speakerId)
    }
  }
  return sortByDisplayOrder(speakers).map((speaker) => ({
    ...speaker,
    sessions: sessionsBySpeakerId.get(speaker.id) ?? [],
  }))
}

export function getEventData() {
  const speakers = sortByDisplayOrder(speakerRecords)
  const speakerMap = buildSpeakerMap(speakers)
  const agendaItems = attachSpeakersToAgenda(agendaRecords, speakerMap)

  return {
    speakers: attachSessionsToSpeakers(speakers, agendaItems),
    agendaItems,
  }
}
