import drUmaPhoto from '../assets/AHT-Speaker-PIC/dr-uma.webp'
import shivaniPhoto from '../assets/AHT-Speaker-PIC/shivani-kulkarni.webp'
import ujjvalaPhoto from '../assets/AHT-Speaker-PIC/ujjvala-ballal.webp'
import snehaPhoto from '../assets/AHT-Speaker-PIC/sneha-bhonsle.webp'
import drBhaskarPhoto from '../assets/AHT-Speaker-PIC/dr-bhaskar.webp'
import drAjitPhoto from '../assets/AHT-Speaker-PIC/dr-ajit-audipudi.webp'
import darioPhoto from '../assets/AHT-Speaker-PIC/dario-heymann.webp'
import anirudhPhoto from '../assets/AHT-Speaker-PIC/anirudh-iyer.jpg'
import kirtiPhoto from '../assets/AHT-Speaker-PIC/kirti-yadav.jpg'
import saarthakPhoto from '../assets/AHT-Speaker-PIC/dr-saarthak-bakshi.jpg'
import anupPhoto from '../assets/AHT-Speaker-PIC/dr-anup-warrier.jpg'
import muthuPhoto from '../assets/AHT-Speaker-PIC/dr-muthu-dhandapani.jpg'
import smitaPhoto from '../assets/AHT-Speaker-PIC/smita-malipatil.jpg'
import drAmitRajPhoto from '../assets/AHT-Speaker-PIC/dr-amit-raj.webp'
import drAnandSivaramanPhoto from '../assets/AHT-Speaker-PIC/dr-anand-sivaraman.webp'
import drKaramveerPhoto from '../assets/AHT-Speaker-PIC/dr-karamveer-chhabra.webp'
import vivekRajagopalPhoto from '../assets/AHT-Speaker-PIC/vivek-rajagopal.webp'
import vsVenkateshPhoto from '../assets/AHT-Speaker-PIC/vs-venkatesh.webp'
import kaminiShivalkarPhoto from '../assets/AHT-Speaker-PIC/kamini-shivalkar.webp'
import raghuvamshiThakurPhoto from '../assets/AHT-Speaker-PIC/raghuvamshi-thakur.webp'
import ashimaSetiaPhoto from '../assets/AHT-Speaker-PIC/ashima-setia.webp'
import khanjanKotechaPhoto from '../assets/AHT-Speaker-PIC/khanjan-kotecha.webp'
import drMridulRampalPhoto from '../assets/AHT-Speaker-PIC/dr-mridul-rampal.webp'
import ravindraMkPhoto from '../assets/AHT-Speaker-PIC/ravindra-mk.webp'
import gayathriVivekanandanPhoto from '../assets/AHT-Speaker-PIC/gayathri-vivekanandan.webp'
import drVamsiKrishnaPhoto from '../assets/AHT-Speaker-PIC/dr-vamsi-krishna.webp'
import drRameshKarmegamPhoto from '../assets/AHT-Speaker-PIC/dr-ramesh-karmegam.webp'
import bharatGuptaPhoto from '../assets/AHT-Speaker-PIC/bharat-gupta.webp'
import samirKarpePhoto from '../assets/AHT-Speaker-PIC/samir-karpe.webp'
import prodocLogo from '../assets/Partner Logo/prodoc-logo.webp'
import hxaiLogo from '../assets/Partner Logo/hxai-logo.webp'
import tobeLogo from '../assets/Partner Logo/tobe-logo.webp'
import certinalLogo from '../assets/Partner Logo/certinal-logo.webp'

const speakerRecords = [
  {
    id: 'speaker-shivani-kulkarni',
    name: 'Shivani Kulkarni',
    title: 'Vice President',
    organization: 'PrimeVP',
    tagline: 'Early Stage Tech VC — Fintech, Marketplaces & Consumer',
    biography:
      'Shivani Kulkarni is a venture capital investor focused on early-stage technology companies across Fintech, Marketplaces, and Consumer segments. As Vice President at PrimeVP, she has built a portfolio spanning financial infrastructure, embedded finance, and D2C brands. Prior to PrimeVP, she led venture investments at Flipkart where she backed companies including Finbox, Hyperface, GOAT Brand Labs, and Ninjacart. She started her career in Investment Banking at Avendus Capital. Shivani holds an MBA in Finance from XLRI Jamshedpur (Director\'s Merit List) and a Gold Medal in Electronics & Communication Engineering from PES University.',
    photoUrl: shivaniPhoto,
    linkedinUrl: 'https://www.linkedin.com/in/kulkarnishivani/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 1,
    expertise: ['Venture Capital', 'Fintech', 'Marketplaces', 'Consumer Tech', 'Early Stage Investing'],
    highlights: [
      { label: 'Current', value: 'Vice President, PrimeVP' },
      { label: 'Previously', value: 'Venture Investments, Flipkart' },
      { label: 'Portfolio', value: 'Finbox · Hyperface · GOAT Brand Labs · Ninjacart' },
      { label: 'Also Investing In', value: 'Elchemy · Navadhan Capital · Metafin' },
    ],
    education: [
      {
        degree: 'MBA, Finance',
        institution: 'XLRI Jamshedpur',
        year: '2018',
        achievement: "Director's Merit List",
      },
      {
        degree: 'B.E., Electronics & Communication Engineering',
        institution: 'PES University, Bangalore',
        year: '2016',
        achievement: 'Gold Medallist',
      },
    ],
    awards: [
      "Director's Merit List — XLRI Jamshedpur, 2017",
      'Gold Medal — PES University, 2016',
    ],
  },
  {
    id: 'speaker-dr-uma-nambiar',
    name: 'Dr. Uma Nambiar',
    title: 'CEO, IISc Medical School Foundation',
    organization: 'IISc Medical School Foundation',
    tagline: 'Neurosurgeon · Healthcare Administrator · Digital Health Pioneer',
    biography:
      'Dr. Uma Nambiar is a trained neurosurgeon and healthcare administrator with over forty years in the healthcare industry. An alumna of Armed Forces Medical College Pune, Sree Chitra Tirunal Institute Trivandrum, and Faculty of Management Studies Delhi, she has also trained at Beth Israel Hospital New York and Necker Enfant Malades Paris. She has worked across India and Africa as a Surgical Neuro-oncologist and in CXO roles at leading corporate hospitals. Dr. Nambiar has commissioned greenfield hospitals and re-engineered brownfield hospitals across multiple geographies, served as Special Technical Advisor to the Ministry of Health in Djibouti, and as a Digital Health consultant to a private hospital group in Botswana. She is an Independent Board Director for Hemas Hospital Group, Sri Lanka and IIHMR Bangalore, and an Honorary Professor at Jawaharlal Nehru Centre for Advanced Scientific Research.',
    photoUrl: drUmaPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 2,
    expertise: ['Neurosurgery', 'Digital Health', 'Healthcare Administration', 'Telemedicine', 'Hospital Commissioning'],
    highlights: [
      { label: 'Current', value: 'CEO, IISc Medical School Foundation' },
      { label: 'Co-Founder', value: 'DHIA — Digital Health India Association' },
      { label: 'Board Director', value: 'Hemas Hospital Group, Sri Lanka' },
      { label: 'Board Director', value: 'IIHMR, Bangalore' },
      { label: 'VP', value: 'Telemedicine Society of India' },
    ],
    education: [
      { degree: 'MBBS', institution: 'Armed Forces Medical College, Pune', year: '1982', achievement: '' },
      { degree: 'M.S. (General Surgery)', institution: 'Armed Forces Medical College, Pune', year: '1990', achievement: '' },
      { degree: 'M.Ch. (Neurosurgery)', institution: 'Sree Chitra Tirunal Institute, Trivandrum', year: '1993', achievement: '' },
      { degree: 'MBA, Healthcare Administration', institution: 'Faculty of Management Studies, Delhi University', year: '2005', achievement: '' },
      { degree: 'Visiting Fellowship — Vascular Neurosurgery', institution: 'Mayo Clinic, Minnesota', year: '1997', achievement: '' },
      { degree: 'Visiting Fellowship — Pediatric Neurosurgery', institution: 'Beth Israel Hospital, New York', year: '1998', achievement: '' },
    ],
    awards: [
      'Excellence in Digital Health Award — UAE Healthcare Leaders\' Summit, 2024',
      'Global Healthcare Digital Women Leadership of the Year — World Health Congress, 2021',
      'Top 50 Strategists in Healthcare to Follow — Medgate Today, 2021',
      'CXO Health Excellence Award — 7th CXO Digital Innovation Health Summit, 2022',
      'Winner, Commonwealth Digital Health Award in Nursing Informatics, 2017',
      'Innovator in Healthcare — Women Leadership and Innovation Award, 2013',
      'Country Development Marketplace Award — World Bank, 2004',
    ],
  },
  {
    id: 'speaker-ujjvala-ballal-shetty',
    name: 'Ujjvala Ballal Shetty',
    title: 'CEO',
    organization: 'Aveksha Hospitals',
    tagline: 'Healthcare Entrepreneur · Lawyer · Advocate for Accessible Care',
    biography:
      'Ujjvala Ballal Shetty is an entrepreneur, lawyer, and committed advocate for accessible healthcare. As CEO of Aveksha Multi-Specialty Hospitals — a growing hospital group in North Bangalore — she is dedicated to delivering world-class healthcare at an affordable cost. Aveksha currently operates a flagship 125-bed branch at MS Palya, serving the community for over 13 years, with a new branch in Yelahanka launching in July 2026. Ujjvala began her career with Inclusive Planet, a startup that successfully changed Indian copyright law to improve literary access for the visually impaired, before practising with a senior litigation lawyer in Bangalore and transitioning into healthcare leadership. She also co-hosts an ongoing online series on Medico-Legal Issues for doctors, alongside Dr. RK Mani and Dr. Shashi Kumar of Cloud Physician.',
    photoUrl: ujjvalaPhoto,
    photoPosition: 'center 18%',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 3,
    expertise: ['Healthcare Leadership', 'Hospital Operations', 'Medico-Legal', 'Entrepreneurship', 'Accessible Healthcare'],
    highlights: [
      { label: 'Current', value: 'CEO, Aveksha Multi-Specialty Hospitals' },
      { label: 'Hospitals', value: 'MS Palya (125 beds, 13+ yrs) · Yelahanka (launching Jul 2026)' },
      { label: 'Background', value: 'Law · Inclusive Planet · Litigation Practice' },
      { label: 'Series', value: 'Co-host, Medico-Legal Issues for Doctors' },
    ],
    education: [
      {
        degree: 'LLB (Law)',
        institution: 'ULC, Bangalore',
        year: '',
        achievement: 'Vice President, AIESEC India',
      },
    ],
    awards: [],
  },
  {
    id: 'speaker-sneha-bhonsle',
    name: 'Sneha Bhonsle',
    title: 'Founder',
    organization: 'Benevolent Legal',
    tagline: 'Healthcare and life sciences lawyer',
    biography:
      'Sneha Bhonsle is the Founder of Benevolent Legal and a healthcare and life sciences lawyer specializing in medical law, healthcare regulation, digital health, and data protection. She advises hospitals, healthcare professionals, and healthtech startups on regulatory, compliance, and medico-legal matters. With experience spanning healthcare, technology, and law, including a stint as Legal & Compliance Consultant at CARPL.ai, Sneha brings valuable insights into the evolving legal landscape of healthcare innovation.',
    photoUrl: snehaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 4,
    expertise: ['Medical Law', 'Healthcare Regulation', 'Digital Health', 'Data Protection', 'Medico-Legal'],
    highlights: [
      { label: 'Current', value: 'Founder, Benevolent Legal' },
      { label: 'Previously', value: 'Legal & Compliance Consultant, CARPL.ai' },
      { label: 'Specialisation', value: 'Medical Law · Healthcare Regulation · Digital Health · Data Protection' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-bhaskar-rajakumar',
    name: 'Dr Bhaskar Rajakumar',
    title: 'CEO, Centre of Excellence in Health Tech and Med Tech',
    organization: 'Govt of Karnataka',
    tagline: 'Evangelising med tech and health innovations, supporting AI driven solutions for Public Health, One Health and Climate Change.',
    biography:
      'A physician by academia, specialised in radiology with masters in business administration. With ~ 20 years across clinical, non-clinical and administrative fields, Dr Bhaskar\'s expertise spans across public health, healthcare administration, insurance, medical affairs, regulatory and pharmacovigilance, medical education, public policy, disaster management and healthcare innovation.\nHe is currently the CEO of Centre of Excellence in Health Tech and Med Tech, Govt of Karnataka and also serves as advisory for Bangalore Bio Innovation Centre, GoK and AI & Robotics Technology Park (ARTPARK), IISc. His present focus is on evangelising med tech and health innovations, supporting AI driven solutions for Public Health, One Health and Climate Change.\nHe is also Adjunct faculty at Rajiv Gandhi University of Medical Sciences, Karnataka and Post Graduate Institute of Medical Education and Research at Chandigarh, teaching healthcare informatics and related subjects.\nPrior to this he was working as the OSD to the Chief Commissioner, BBMP and was heading the Covid 19 Central War Room at BBMP.\nHis earlier startup \'Mediknit\' was focused on integration of future technologies in healthcare education, and worked with more than 1 million healthcare professionals across India, APAC, and USA. His work on healthcare and innovations have received multiple accolades and recognitions across the globe.\nHe has volunteered across the globe - including during the major disasters such as Tsunami in Tamil Nadu, Earth Quake in Nepal, Bomb blasts in Brussels etc.,\nPart of passion he is an avid runner with multiple marathons completed across the country and practices theatre.',
    photoUrl: drBhaskarPhoto,
    linkedinUrl: 'https://www.linkedin.com/in/drbhaskar/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 5,
    expertise: ['MedTech', 'HealthTech', 'Public Health', 'AI in Healthcare', 'Healthcare Innovation', 'Digital Health'],
    highlights: [
      { label: 'Current', value: 'CEO, Centre of Excellence in Health Tech and Med Tech, GoK' },
      { label: 'Advisory', value: 'Bangalore Bio Innovation Centre · ARTPARK, IISc' },
      { label: 'Faculty', value: 'RGUHS Karnataka · PGIMER Chandigarh' },
      { label: 'Founder', value: 'Mediknit — 1M+ healthcare professionals across India, APAC & USA' },
    ],
    education: [
      { degree: 'MBBS (Radiology specialisation)', institution: '', year: '', achievement: '' },
      { degree: 'MBA', institution: '', year: '', achievement: '' },
    ],
    awards: [
      'Top 100 Healthcare Leaders — Global Listing, 2018',
      'Top 50 Smart Health Leaders — Global, 2018',
      'Namma Bengaluru Healthcare Professional of the Year, 2021',
      'Deccan Herald Covid Warrior Award, 2022',
      'Covid Warrior Award — St Joseph\'s University, 2022',
      'Speaker at multiple national and international conferences',
    ],
  },
  {
    id: 'speaker-dr-ajit-audipudi',
    name: 'Dr. Ajit Audipudi',
    title: 'General Surgeon & Healthcare AI Strategist',
    organization: 'SVS Medical College & Hospital | AdaptAI Health Tech',
    tagline: 'Helping healthcare organizations move from AI curiosity to AI adoption.',
    biography:
      'Dr. Ajit Audipudi is a General Surgeon, Healthcare AI Strategist, and Director of the AI Research Wing at SVS Medical College & Hospital, India. He is also Co-Founder of AdaptAI Health Tech, where he focuses on the practical implementation of artificial intelligence in healthcare.\nHis work centers on helping healthcare organizations move from AI curiosity to AI adoption through clinical workflow integration, healthcare AI strategy, research systems, and implementation frameworks. He is involved in developing AI-enabled healthcare solutions, clinical data registries, and research initiatives that support evidence generation, quality improvement, and digital transformation in healthcare.\nDr. Audipudi works at the intersection of medicine, healthcare research, and emerging technologies, with a particular interest in translating AI from proof-of-concept into real-world clinical practice. He has served as a speaker, subject matter expert, and workshop lead on artificial intelligence in healthcare for clinicians, healthcare professionals, and academic audiences.',
    photoUrl: drAjitPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 6,
    expertise: ['Healthcare AI', 'Clinical AI Implementation', 'AI Strategy', 'General Surgery', 'Digital Health Transformation'],
    highlights: [
      { label: 'Director', value: 'AI Research Wing, SVS Medical College & Hospital' },
      { label: 'Co-Founder', value: 'AdaptAI Health Tech Pvt Ltd' },
      { label: 'Focus', value: 'Translating AI from proof-of-concept to real-world clinical practice' },
      { label: 'Engagements', value: 'Speaker, subject matter expert & workshop lead on AI in healthcare' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-anirudh-iyer',
    name: 'Anirudh Iyer',
    title: 'Vice President, Investments',
    organization: 'Xeed Ventures',
    tagline: 'Partnering with early-stage founders to build scalable businesses',
    biography:
      'Anirudh Iyer is Vice President for Investments at Xeed Ventures, where he partners with early-stage founders building tech-first and tech-enabled businesses from their first conviction cheque through scale. He focuses on sourcing and evaluating investments, working closely with portfolio companies, and developing strategic frameworks that help founders navigate growth.\nAt Xeed Ventures, Anirudh has worked with startups across SaaS, AI, fintech, enterprise technology, and consumer technology.\nAs an early-stage investor, Anirudh works closely with founders on investment readiness, business strategy, fundraising, and scaling technology businesses. His interests span emerging technologies, venture investing, and helping entrepreneurs build category-defining companies from inception to growth.\nAnirudh is also a CAIA (Chartered Alternative Investment Analyst) Charterholder, reflecting his expertise in alternative investments, venture capital, private equity, and portfolio management.',
    photoUrl: anirudhPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 8,
    expertise: ['Venture Capital', 'Early Stage Investing', 'SaaS', 'AI', 'Fintech', 'Alternative Investments'],
    highlights: [
      { label: 'Current', value: 'Vice President, Investments — Xeed Ventures' },
      { label: 'Focus', value: 'Tech-first & tech-enabled early-stage startups' },
      { label: 'Sectors', value: 'SaaS · AI · Fintech · Enterprise Tech · Consumer Tech' },
      { label: 'Credential', value: 'CAIA Charterholder — Chartered Alternative Investment Analyst' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-kirti-yadav',
    name: 'Kirti Yadav',
    title: 'Head, Integrated Marketing & SBU Head, Rehabilitation',
    organization: 'MAIINS, Marengo Asia Hospitals',
    tagline: 'Healthcare Growth Strategist | AI-Driven Marketing & Rehabilitation Leader',
    biography:
      'Kirti Yadav is a healthcare business leader with over 16 years of experience spanning healthcare marketing, business development, rehabilitation, home healthcare, and digital health. She currently leads Integrated Marketing and the Rehabilitation Business Unit at MAIINS (Marengo Asia Institute of Neurosciences & Spine), one of India\'s leading neuroscience institutes under Marengo Asia Hospitals, Gurugram.\nWith a unique blend of clinical expertise as a physiotherapist and commercial leadership experience, Kirti has successfully built and scaled healthcare businesses, developed high-performing teams, and driven sustainable growth across hospitals, rehabilitation services, and home healthcare organizations.\nHer expertise lies in healthcare growth strategy, AI-driven patient engagement, integrated marketing, brand building, referral network development, and business transformation. She has played a pivotal role in positioning MAIINS as a leading destination for neuroscience and rehabilitation care through innovative marketing, digital transformation, and stakeholder engagement initiatives.\nKirti is passionate about leveraging technology and artificial intelligence to enhance patient experiences, improve healthcare accessibility, and create scalable growth models for healthcare organizations.',
    photoUrl: kirtiPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 9,
    expertise: ['AI in Healthcare Marketing', 'Digital Transformation in Healthcare', 'Patient Acquisition & Engagement', 'Healthcare Brand Strategy', 'Rehabilitation & Allied Health', 'Business Growth & Revenue Expansion'],
    highlights: [
      { label: 'Current', value: 'Head, Integrated Marketing & SBU Head Rehabilitation — MAIINS, Marengo Asia Hospitals' },
      { label: 'Experience', value: '16+ years in healthcare marketing, business development & rehabilitation' },
      { label: 'Background', value: 'Physiotherapist with commercial leadership expertise' },
      { label: 'Focus', value: 'AI-driven patient engagement · Brand building · Referral network development' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-dario-heymann',
    name: 'Dr. Dario Heymann',
    title: 'Co-founder & Chief Data & Technology Officer',
    organization: 'Galen Growth',
    tagline: "Building the world's leading digital health intelligence platform.",
    biography:
      "Dario co-founded Galen Growth during his PhD, where he serves as Chief Data & Technology Officer. He led the development of HealthTech Alpha, the world's foremost digital health venture intelligence platform. HealthTech Alpha tracks over 70,000 companies and close to two billion data points, enabling AI-powered insights that guide health systems and corporations globally in shaping their digital health strategies.\nUnder Dario's leadership, Galen Growth achieved profitability from its first year and executed over 150 strategic projects for multinational pharmaceutical, insurance, and medical device companies, as well as government organizations.\nDario also advises the Singapore Eye Research Institute and the SingHealth AI Office, focusing on developing AI-powered operational and clinical solutions, with particular focus on the sovereign AI space.\nHe led the commercialisation of Enigma Health in early 2025, which was merged with a US business in 2026.\nPrior to SingHealth and Galen Growth, Dario worked in both academia and pharma in Singapore, China and Germany. He holds a PhD in Material Sciences, specialising in structural biology, as well as master's degrees in Material Sciences, Biochemistry and Molecular Biology.",
    photoUrl: darioPhoto,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 7,
    expertise: ['Digital Health Intelligence', 'HealthTech Strategy', 'AI in Healthcare', 'Sovereign AI', 'Venture Intelligence'],
    highlights: [
      { label: 'Platform', value: 'HealthTech Alpha — 70,000+ companies, ~2B data points' },
      { label: 'Advisory', value: 'Singapore Eye Research Institute · SingHealth AI Office' },
      { label: 'Track Record', value: '150+ strategy projects for pharma, insurers, medtech & governments' },
      { label: 'Special Advisor', value: 'Governments on AI & GenAI integration in healthcare' },
    ],
    education: [
      { degree: 'PhD, Material Sciences (Structural Biology)', institution: '', year: '', achievement: '' },
      { degree: "MSc, Material Sciences", institution: '', year: '', achievement: '' },
      { degree: 'MSc, Biochemistry & Molecular Biology', institution: '', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-anup-warrier',
    name: 'Dr. Anup R. Warrier',
    title: 'Group Chief of Medical Services & Quality',
    organization: 'Aster DM Healthcare',
    tagline: 'Driving clinical excellence, quality & digital transformation across an 18-hospital network.',
    biography:
      'Dr. Anup R. Warrier is Group Chief of Medical Services & Quality at Aster DM Healthcare, where he leads clinical strategy, quality, patient safety, and digital transformation across an 18-hospital network. A physician executive with nearly two decades of experience, his career spans infectious diseases, healthcare quality, clinical governance, accreditation, and enterprise healthcare leadership.\nOver the years, Dr. Warrier has led large-scale initiatives in quality improvement, EMR implementation, AI adoption, greenfield hospital commissioning, and clinical governance — driving measurable improvements in patient safety and healthcare outcomes. He reduced composite HAI rates from 2.0% to 0.9% group-wide, sustained six JCI accreditation cycles, and delivered award-winning reductions in CLABSI and surgical-site infections.\nBeyond his leadership at Aster, he serves in national and international roles focused on infection prevention, antimicrobial stewardship, and healthcare quality, and has contributed extensively to clinical research, policy, and medical education with 30+ peer-reviewed publications.',
    photoUrl: anupPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 11,
    expertise: ['Clinical Governance & Patient Safety', 'Quality Systems (JCI · NABH · ACHSI)', 'Infectious Diseases & Antimicrobial Stewardship', 'EMR & AI / Digital Adoption', 'Greenfield Hospital Commissioning', 'M&A Clinical Due Diligence'],
    highlights: [
      { label: 'Current', value: 'Group Chief of Medical Services & Quality — Aster DM Healthcare (18 hospitals)' },
      { label: 'Impact', value: 'Reduced composite HAI rates from 2.0% → 0.9% group-wide; sustained 6 JCI accreditation cycles' },
      { label: 'External Roles', value: 'Chairperson, CAHO IPC Forum · Faculty, WHO Infection Prevention programmes · Kerala AMR Committee' },
      { label: 'Research', value: '30+ peer-reviewed publications — antimicrobial resistance, infection prevention, sepsis & implementation science' },
    ],
    education: [
      { degree: 'INSEAD — Leadership Programme for Senior Executives (ILPSE)', institution: '', year: 'Ongoing', achievement: '' },
      { degree: 'Harvard Medical School — AI in Healthcare', institution: '', year: 'Ongoing', achievement: '' },
      { degree: 'DNB, General Medicine', institution: '', year: '', achievement: '' },
      { degree: 'MBBS', institution: 'Government Medical College, Trivandrum', year: '', achievement: '' },
    ],
    awards: [
      'SHEA International Ambassador Award',
      'Healthcare Management Asia Award 2016',
      'Healthcare Management Asia Award 2019',
      'SHEA International Research Grant',
      'IDSA Centre of Excellence Recognition',
      'ESCMID European Centre for Collaboration Recognition',
    ],
  },
  {
    id: 'speaker-smita-malipatil',
    name: 'Smita Malipatil',
    title: 'Founder & CEO',
    organization: 'Hosa Health',
    tagline: 'Building a pediatric intelligence layer for Gen Alpha Healthcare.',
    biography:
      'Smita Malipatil is the Founder & CEO of Hosa Health, building a pediatric intelligence layer for Gen Alpha Healthcare.\nSmita began her entrepreneurial journey as the founder of Kieon, one of the UK\'s pioneering digital transformation agencies. Under her leadership, Kieon expanded its operations across the UK, US, and India — culminating in a successful exit to a major UK PLC. Post her exit, she was CEO for two companies in the Deeptech and AI/ML sectors, where she successfully scaled the organizations and led them through key stages of growth.\nAn alumna of Harvard Business School, Smita is a passionate advocate for entrepreneurship and women in leadership. She is an angel investor and startup mentor, and serves as a Founding Member of the India-UK Responsible AI Group, a committee member of the Start-up Vision Group Karnataka, and Board and Charter Member at TiE Bangalore.',
    photoUrl: smitaPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/bigchief/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 13,
    expertise: ['Pediatric Digital Health', 'AI/ML & Deeptech', 'Digital Transformation', 'Entrepreneurship & Exits', 'Angel Investing', 'Responsible AI'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO — Hosa Health (pediatric intelligence layer for Gen Alpha)' },
      { label: 'Previous', value: 'Founder, Kieon — UK digital transformation agency; successful exit to major UK PLC' },
      { label: 'Leadership', value: 'CEO at two Deeptech & AI/ML companies post-exit; scaled through key growth stages' },
      { label: 'Community', value: 'Founding Member, India-UK Responsible AI Group · TiE Bangalore Board & Charter Member' },
    ],
    education: [
      { degree: 'Harvard Business School', institution: '', year: '', achievement: 'Alumna' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-muthu-dhandapani',
    name: 'Dr. Muthu Dhandapani',
    title: 'Vice President — Quality & Regulatory Compliance',
    organization: 'Tricog Health',
    tagline: 'Bridging innovation, regulation & commercialization across medical devices & AI-powered digital health.',
    biography:
      'Dr. Dhandapani is a strategic and execution-driven leader with 22 years of regulatory experience across India, USA, and EU — building and scaling medical device, diagnostics, and digital health functions. He has proven success in leading product development, R&D and manufacturing facility setup, regulatory affairs, quality systems, multicentric clinical studies, AI/ML-based SaMD (Software as a Medical Device), and cloud-connected medical platforms.\nHe brings strong command over global regulations including CDSCO, FDA, ISO 13485, IEC 62304, MDSAP, EU IVDR, and MDR, with deep leadership experience in new product development, clinical validation, software lifecycle management, and international market access.\nBeyond his industry role, Dr. Dhandapani serves as a mentor on the board of 12 bio-incubators and TBIs including BBC, C-CAMP, ISB, MS Ramaiah, JSS Mysuru, STPI, IIT Guwahati, Yenepoya, and GINSERV.',
    photoUrl: muthuPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 12,
    expertise: ['Medical Device Regulation (CDSCO · FDA · EU MDR)', 'AI/ML SaMD & Digital Health', 'Quality Systems (ISO 13485 · MDSAP)', 'Clinical Validation & Studies', 'R&D & Manufacturing Setup', 'Startup Mentorship & Incubation'],
    highlights: [
      { label: 'Current', value: 'VP, Quality & Regulatory Compliance — Tricog Health' },
      { label: 'Experience', value: '22 years across India, USA & EU in medical devices, diagnostics & digital health' },
      { label: 'Expertise', value: 'AI/ML SaMD · Cloud-connected medical platforms · International market access · MDSAP · EU IVDR' },
      { label: 'Mentorship', value: 'Board mentor at 12 bio-incubators & TBIs — BBC, C-CAMP, ISB, IIT Guwahati, STPI & more' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-amit-raj',
    name: 'Dr. Amit Raj',
    title: 'Founder & CEO, Plexus AI | Cardiologist',
    organization: 'Plexus AI / Plexus Medcare Hospital',
    tagline: 'Building clinical AI infrastructure that makes AI safe, trusted and deployable at bedside.',
    biography:
      'Dr. Amit Raj is a cardiologist, hospital leader, and healthcare entrepreneur dedicated to bridging the gap between healthcare AI innovation and real-world clinical adoption.\nAs Founder & CEO of Plexus AI and Managing Director of Plexus Medcare Hospital, he is building infrastructure that connects clinical practice with AI innovation. Through Plexus AI\'s hospital-based platform, he enables AI startups, hospitals, and healthcare organizations to navigate three critical stages: Validation → Deployment → Market Access.\nThis framework ensures AI solutions are clinically validated, responsibly governed, and scaled through real-world evidence and physician-led implementation. His work focuses on making AI safe, practical, and scalable within everyday clinical workflows — not confined to laboratories or theoretical environments.\nHe believes the future of healthcare will be defined not only by smarter algorithms, but by the ability to responsibly integrate AI into patient care. His vision is to position India as a global leader in trusted clinical AI validation, deployment, and innovation, improving healthcare outcomes through safe and evidence-driven adoption.',
    photoUrl: drAmitRajPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/doctoramitraj',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 14,
    expertise: ['Clinical AI Validation', 'Real-World Evidence', 'Hospital AI Deployment', 'Responsible AI Governance', 'Cardiovascular AI', 'Digital Health Strategy'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO, Plexus AI' },
      { label: 'Also', value: 'Managing Director, Plexus Medcare Hospital' },
      { label: 'Framework', value: 'Clinical AI Validation → Deployment → Market Access' },
      { label: 'Mission', value: 'Positioning India as a global leader in trusted clinical AI' },
    ],
    education: [
      { degree: 'Executive Education', institution: 'Harvard Business School', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'IIM Ahmedabad', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'ISB', year: '', achievement: '' },
    ],
    awards: [
      'ESC | ACC | EAPCI | EBAC Member',
    ],
  },
  {
    id: 'speaker-dr-anand-sivaraman',
    name: 'Dr. Anand Sivaraman',
    title: 'Founder & CEO',
    organization: 'Remidio',
    tagline: 'Reimagining healthcare access through AI-powered medical devices.',
    biography:
      'Dr. Anand Sivaraman is redefining the way healthcare innovation reaches those who need it most, through Remidio — an India-headquartered, AI-enabled medical devices company that has pioneered innovations delivering specialist care to primary care, public health centers, and patient homes, starting with Ophthalmic Care.\nA scientist, entrepreneur, and problem-solver, he earned his Master\'s, PhD and Postdoctoral degrees at MIT, followed by 20 years of experience building novel products out of India in in-vitro diagnostics and optical imaging.\nAnand believes that, in order to create disruptive healthcare access, product innovations need to be combined with both delivery and business model innovations. Traditional medical devices often remain too expensive, complex, and designed for specialists — not keeping the healthcare worker at the last mile in mind. Remidio\'s innovations challenge this model, bringing world-class diagnostics to the last mile with simplicity, efficiency, and affordability.\nHis approach is rooted in a vision for equitable healthcare, where groundbreaking technology is not just developed for the privileged few but designed to work in the real-world conditions of both developing and developed nations. His greatest strength is his ability to turn constraints into catalysts for innovation — seeing challenges like limited infrastructure, affordability gaps, or workforce shortages as opportunities to design smarter, more scalable healthcare solutions.',
    photoUrl: drAnandSivaramanPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 15,
    expertise: ['AI-Powered Medical Devices', 'Ophthalmic Diagnostics', 'Last-Mile Healthcare', 'Medical Innovation', 'Equitable Healthcare Access', 'Optical Imaging'],
    highlights: [
      { label: 'Current', value: 'CEO & Founder, Remidio' },
      { label: 'Focus', value: 'AI-enabled devices bringing specialist care to primary care & patient homes' },
      { label: 'Background', value: '20+ years building novel diagnostics & optical imaging products from India' },
      { label: 'Vision', value: 'Equitable healthcare — world-class diagnostics at the last mile' },
    ],
    education: [
      { degree: 'Postdoctoral Research', institution: 'MIT', year: '', achievement: '' },
      { degree: 'PhD', institution: 'MIT', year: '', achievement: '' },
      { degree: "Master's", institution: 'MIT', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-saarthak-bakshi',
    name: 'Dr. Saarthak Bakshi',
    title: 'Founder & CEO',
    organization: 'Risaa IVF and NEOS Angels',
    tagline: 'Combining healthcare innovation with entrepreneurship to advance fertility care and support the next generation of healthcare startups.',
    biography:
      'Dr. Saarthak Bakshi is the Founder & CEO of RISAA IVF and NEOS Angels, where he combines healthcare innovation with entrepreneurship to advance fertility care and support the next generation of healthcare startups. A serial entrepreneur, investor, and startup mentor, he has guided more than 35 startups while building ventures focused on healthcare, education, and social impact.\nBeyond his entrepreneurial journey, Dr. Bakshi actively contributes to India\'s innovation ecosystem through leadership and advisory roles across healthcare, startup incubators, and industry organizations. His work is driven by a commitment to improving healthcare accessibility, promoting fertility awareness, and enabling innovation through collaboration, mentorship, and investment.',
    photoUrl: saarthakPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/saarthakbakshi/',
    twitterUrl: 'https://x.com/saarthak_bakshi',
    isFeatured: true,
    displayOrder: 10,
    expertise: ['Fertility & IVF', 'Healthcare Innovation', 'Startup Mentorship', 'Venture Investing', 'Social Impact', 'Healthcare Entrepreneurship'],
    highlights: [
      { label: 'Current', value: 'Founder & CEO — RISAA IVF and NEOS Angels' },
      { label: 'Impact', value: 'Mentored & guided 35+ startups across healthcare, education & social impact' },
      { label: 'Roles', value: 'Director, HealthPod Incubator · President, Voice of Healthcare · Founder, IIRFT' },
      { label: 'Mission', value: 'Improving healthcare accessibility · Fertility awareness · Innovation through mentorship' },
      { label: 'Leadership', value: 'AIMA YLC National Brand Communication Chair · CRM Academy of Asia Board of Directors' },
      { label: 'Advisory', value: 'Strategic Advisor & Board Member — INY Foundation · Trustee, Foundation of Healthcare Wellness & Promotion' },
      { label: 'Councils', value: 'Indo-German Young Leaders Forum · CII Young Indians Core Executive Committee · Startup Leadership Program Leader' },
    ],
    education: [],
    awards: [
      '50 Under 50 Healthcare Entrepreneur of the Year 2025',
      'Best Healthcare Entrepreneur of the Year 2025',
      '100 Most Impactful Healthcare Leaders 2024 — World Health & Congress Awards',
      'AIMA Young Leaders Award 2024',
      'Entrepreneur of the Year in Healthcare 2023 & 2024 — Entrepreneur Magazine',
      'National Award in Healthcare — Delhi Management Association 2023',
      'IVF Chain of the Year 2023–25',
      'Best of the Best IVF India Award 2023–24',
      'Best Infertility Clinic India 2023 — Times of India',
      'CSC\'23 Fellow — The Duke of Edinburgh\'s Commonwealth Study Conference, Canada',
      'FORBES 30 Under 30 Asia',
      'BW Healthcare World 40 Under 40',
      'Entrepreneur 35 Under 35',
      'Multiple TEDx Speaker',
    ],
  },
  {
    id: 'speaker-dr-karamveer-chhabra',
    name: 'Dr. Karamveer S. Chhabra',
    title: 'Executive Director',
    organization: 'Alive Wellness Clinics',
    tagline: 'Driving innovation in aesthetic medicine, wellness & patient-centric care',
    biography:
      'Dr. Karamveer S. Chhabra is an Indian aesthetic physician, entrepreneur, and healthcare leader who has emerged as one of the prominent young voices in aesthetic medicine and wellness in India. He currently serves as Executive Director of Alive Wellness Clinics, one of India\'s leading chains in clinical dermatology and aesthetic medicine, with a growing network of clinics across the country.\nWith a unique combination of medical understanding, business strategy, and global exposure, Dr. Chhabra has played a key role in expanding the organization\'s footprint, strengthening its digital ecosystem, and positioning the group among India\'s fast-growing dermatology and aesthetic healthcare brands. Since being appointed Executive Director in 2023, he has contributed significantly to operational expansion, patient experience optimization, and the integration of advanced aesthetic technologies and treatment verticals.\nA graduate of M. S. Ramaiah Medical College, Dr. Chhabra combines evidence-based medicine with a modern understanding of aesthetics, wellness, regenerative medicine, and patient-centric care. His work spans injectables, body contouring, regenerative aesthetics, practice development, and the growing intersection of medicine, technology, and consumer healthcare.\nHe is also the Founder of Alive Institute of Aesthetics, a leading training platform focused on aesthetic medicine education, which has trained 200+ doctors and 400+ support staff in about three years, with collaborative programs alongside globally recognized brands including APTOS and Merz Aesthetics. Dr. Chhabra has been recognized by The Times of India for his contributions to aesthetic medicine, healthcare entrepreneurship, and clinical management.',
    photoUrl: drKaramveerPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 16,
    expertise: ['Aesthetic Medicine', 'Regenerative Aesthetics', 'Healthcare Entrepreneurship', 'Practice Development', 'Wellness & Patient Care'],
    highlights: [
      { label: 'Current', value: 'Executive Director, Alive Wellness Clinics' },
      { label: 'Founder', value: 'Alive Institute of Aesthetics' },
      { label: 'Training Impact', value: '200+ doctors & 400+ support staff trained in ~3 years' },
      { label: 'Recognition', value: 'Recognized by The Times of India for aesthetic medicine & healthcare leadership' },
      { label: 'International', value: 'Faculty speaker — IMCAS World Congress, AMWC, MAIS Summit (Spain)' },
    ],
    education: [
      { degree: 'MBBS', institution: 'M. S. Ramaiah Medical College', year: '', achievement: '' },
    ],
    awards: [
      'Recognized by The Times of India for achievements in aesthetic medicine & healthcare entrepreneurship',
    ],
  },
  {
    id: 'speaker-vivek-rajagopal',
    name: 'Vivek Rajagopal',
    title: 'Group Chief Analytics & AI Officer',
    organization: 'Narayana Health',
    tagline: 'Leading AI-driven clinical & operational transformation that delivers better care and outcomes',
    biography:
      'Vivek Rajagopal is the Group Chief Analytics & AI Officer at Narayana Health, one of India\'s largest hospital chains. Over the past 15 years, he has not only led but also founded the organisation\'s Analytics & AI division — Medha AI, building it into a central driver of transformation, advancing clinical care, optimising operations, enhancing patient engagement, and strengthening financial outcomes. He combines this deep industry experience with a PGDM from the prestigious Indian Institute of Management Bangalore (IIMB).',
    photoUrl: vivekRajagopalPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 17,
    expertise: ['Healthcare Analytics', 'Artificial Intelligence', 'Clinical Transformation', 'Operations Optimization', 'Patient Engagement'],
    highlights: [
      { label: 'Current', value: 'Group Chief Analytics & AI Officer, Narayana Health' },
      { label: 'Founder', value: 'Medha AI — Narayana Health\'s Analytics & AI division' },
      { label: 'Experience', value: '15+ years leading AI-driven clinical & operational transformation' },
      { label: 'Focus', value: 'Clinical care · Operations · Patient engagement · Financial outcomes' },
    ],
    education: [
      { degree: 'PGDM', institution: 'Indian Institute of Management, Bangalore (IIMB)', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-vs-venkatesh',
    name: 'V.S. Venkatesh',
    title: 'Managing Director',
    organization: 'Zentor Medtech Pvt Ltd',
    tagline: 'Transforming healthcare businesses through strategy, leadership & innovation',
    biography:
      'Venkatesh is a seasoned business consultant and startup mentor with over three decades of experience in the global healthcare sector. His expertise spans 360 degrees across pharmaceuticals, hospitals, diagnostics, and health tech & medtech, with a proven track record of steering organizations toward sustainable growth and excellence.\nAs a strategic leader, he has held C-level positions with renowned brands, including Apollo Hospitals, SRL Ranbaxy, Zydus Cadila, Bourn Hall (UK), and JDC (UAE).\nTrained at leading institutions like IIM-Ahmedabad, Harvard Business School, and Wharton, Venkatesh provides advisory services and mentorship to first-generation entrepreneurs and established businesses seeking professionalization or strategic turnarounds. He was also instrumental in taking GST successfully into the IPO. His unique approach combines critical business tactics with a deep understanding of organizational culture, focusing on the creative and expressive dimensions of leadership.\nA keynote speaker, Venkatesh has addressed audiences in over 15 countries on topics ranging from healthcare technology and management change to medical tourism. He has received numerous awards for his leadership and public speaking, including "CEO of the Year" (Dubai, 2017) and "Best International Speaker" (India, 2016).',
    photoUrl: vsVenkateshPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 18,
    expertise: ['Healthcare Strategy', 'Business Consulting', 'Startup Mentorship', 'Pharma & Medtech', 'Organizational Leadership'],
    highlights: [
      { label: 'Current', value: 'Managing Director, Zentor Medtech Pvt Ltd' },
      { label: 'Previously', value: 'C-level roles — Apollo Hospitals · SRL Ranbaxy · Zydus Cadila · Bourn Hall (UK) · JDC (UAE)' },
      { label: 'Experience', value: '30+ years across pharmaceuticals, hospitals, diagnostics & medtech' },
      { label: 'Speaking', value: 'Keynote speaker in 15+ countries on healthcare tech, management change & medical tourism' },
    ],
    education: [
      { degree: 'Executive Education', institution: 'IIM Ahmedabad', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'Harvard Business School', year: '', achievement: '' },
      { degree: 'Executive Education', institution: 'Wharton School', year: '', achievement: '' },
    ],
    awards: [
      'CEO of the Year — Dubai, 2017',
      'Best International Speaker — India, 2016',
    ],
  },
  {
    id: 'speaker-kamini-shivalkar',
    name: 'Kamini Shivalkar',
    title: 'AVP - Investments',
    organization: 'Gemba Capital',
    tagline: 'Backing the next generation of health & consumer startups',
    biography:
      "Kamini Shivalkar currently works as an AVP in the investment team at Gemba Capital, an early-stage VC fund focused on Fintech and Consumer tech. She has 8 years of experience in early-stage investing and currently writes 'The Burn Rate', a weekly intelligence debrief on India's health and wellness boom for founders, investors, and operators.\nPrior to her role as an investor, she served as a Business Analyst at Indus Valley Partners and was an early team member at Byju's. She holds a Master's from JBIMS and a B.Tech from VNIT. Outside of work, she has completed high-altitude Himalayan treks and runs marathons and trail runs across India.",
    photoUrl: kaminiShivalkarPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 19,
    expertise: ['Venture Capital', 'Fintech', 'Consumer Tech', 'Early Stage Investing', 'Health & Wellness'],
    highlights: [
      { label: 'Current', value: 'AVP - Investments, Gemba Capital' },
      { label: 'Writes', value: "'The Burn Rate' — weekly intelligence debrief on India's health & wellness boom" },
      { label: 'Previously', value: "Business Analyst, Indus Valley Partners · Early team member, Byju's" },
      { label: 'Experience', value: '8 years in early-stage investing' },
    ],
    education: [
      { degree: "Master's", institution: 'JBIMS', year: '', achievement: '' },
      { degree: 'B.Tech', institution: 'VNIT', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-raghuvamshi-thakur',
    name: 'Raghuvamshi Thakur',
    title: 'Co-founder',
    organization: 'Prodoc AI',
    tagline: 'Transforming patient care through conversational and agentic AI',
    biography:
      'Raghuvamshi Thakur is the Co-founder of Prodoc AI, a healthcare AI company transforming patient engagement through conversational and agentic AI. He leads product strategy and innovation, helping hospitals automate patient journeys across preventive care, surgery, recovery, and chronic disease management.\nHis work focuses on combining large language models, specialized healthcare AI, and workflow automation to improve patient outcomes while reducing operational complexity. Under his leadership, Prodoc AI has partnered with over 100 healthcare providers and impacted more than one million patients. Raghuvamshi is passionate about building practical AI products that make healthcare more accessible, personalized, and measurable.',
    photoUrl: raghuvamshiThakurPhoto,
    photoPosition: 'center top',
    linkedinUrl: 'https://www.linkedin.com/in/raghuvamshithakur/',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 20,
    expertise: ['Conversational AI', 'Agentic AI', 'Healthcare AI', 'Patient Engagement', 'Workflow Automation'],
    highlights: [
      { label: 'Current', value: 'Co-founder, Prodoc AI' },
      { label: 'Focus', value: 'Automating patient journeys — preventive care, surgery, recovery & chronic disease management' },
      { label: 'Impact', value: '100+ healthcare providers partnered · 1M+ patients impacted' },
      { label: 'Approach', value: 'LLMs + specialized healthcare AI + workflow automation' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-ashima-setia',
    name: 'Ashima Setia',
    title: 'Principal',
    organization: 'Sorin Investments',
    tagline: 'Backing category-defining health tech and med tech ventures',
    biography:
      'Ashima Setia brings a cross-functional background spanning consulting, operations, and investing. At McKinsey, she worked with life sciences clients including global CROs. She later led the insurance vertical at MediBuddy, driving the business to profitability.\nShe is currently a Principal at Sorin Investments, where her portfolio includes Nivaan Care. Her focus areas span insurance-linked health models and scalable care delivery platforms, with a broader mandate backing category-defining health tech and med tech ventures across insurance, care delivery, and life sciences innovation.',
    photoUrl: ashimaSetiaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 21,
    expertise: ['Health Tech Investing', 'Insurance', 'Care Delivery', 'Life Sciences', 'Venture Investing'],
    highlights: [
      { label: 'Current', value: 'Principal, Sorin Investments' },
      { label: 'Portfolio', value: 'Nivaan Care' },
      { label: 'Previously', value: 'Led insurance vertical at MediBuddy, driving it to profitability · McKinsey (life sciences, global CROs)' },
      { label: 'Focus', value: 'Insurance-linked health models & scalable care delivery platforms' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-khanjan-kotecha',
    name: 'Khanjan Kotecha',
    title: 'VP of Products',
    organization: 'Certinal',
    tagline: 'Building trusted AI & compliance infrastructure for healthcare',
    biography:
      "Khanjan is a technologist who builds products for regulated industries. As VP of Products at Certinal, a data privacy, consent, and compliance platform, he leads product for healthcare and life sciences. He builds AI-driven workflows that solve two hard problems at once: making eSignatures hold up as legally valid clinical consent and keeping pace with India's Digital Personal Data Protection (DPDP) Act.\nOver 12+ years, he has built products across trust and verification infrastructure, growth-stage SaaS, and two-sided marketplaces. His focus has consistently been the same: making technology that regulated, high-stakes organizations can actually trust and adopt.",
    photoUrl: khanjanKotechaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 22,
    expertise: ['Product Management', 'AI Compliance', 'eSignatures', 'Data Privacy', 'Healthcare & Life Sciences'],
    highlights: [
      { label: 'Current', value: 'VP of Products, Certinal' },
      { label: 'Focus', value: 'AI-driven workflows for legally valid clinical consent & DPDP Act compliance' },
      { label: 'Experience', value: '12+ years across trust & verification infrastructure, growth-stage SaaS & two-sided marketplaces' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-vamsi-krishna',
    name: 'Dr. Vamshi Krishna A',
    title: 'Chief Growth Officer',
    organization: 'Apollo Radiology International',
    tagline: 'Driving the future of AI-powered diagnostics & global radiology innovation',
    biography:
      "Dr. Vamshi Krishna A is the Chief Growth Officer at Apollo Radiology International (ARI), where he leads strategic growth, partnerships, and global expansion initiatives across one of the world's leading teleradiology networks. ARI supports hundreds of hospitals and diagnostic centers across India and multiple international markets, helping healthcare providers improve access to expert radiology services and diagnostic excellence.\nWith over two decades of experience in healthcare and business leadership, Dr. Vamshi has been at the forefront of driving innovation in diagnostic imaging, digital health, and AI-enabled healthcare solutions. He works closely with healthcare organizations, technology partners, and clinical teams to bridge the gap between emerging technologies and real-world clinical adoption.\nA strong advocate for the responsible use of AI in healthcare, Dr. Vamshi is actively involved in conversations around radiology transformation, workflow innovation, clinical trust, and the future of diagnostics. His expertise spans healthcare growth strategy, digital transformation, global healthcare partnerships, and the integration of AI into clinical workflows.",
    photoUrl: drVamsiKrishnaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 24,
    expertise: ['Healthcare Growth Strategy', 'AI-Powered Diagnostics', 'Teleradiology', 'Digital Transformation', 'Global Healthcare Partnerships', 'Clinical AI Adoption'],
    highlights: [
      { label: 'Current', value: 'Chief Growth Officer, Apollo Radiology International' },
      { label: 'Experience', value: '20+ years in healthcare and business leadership' },
      { label: 'Reach', value: 'Strategic growth & global expansion across hundreds of hospitals & diagnostic centers' },
      { label: 'Focus', value: 'AI-enabled diagnostic imaging, workflow innovation & clinical trust' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-mridhul',
    name: 'Dr. Mridul Rampal',
    title: 'Co-Founder and Chief Medical Officer',
    organization: '2care.ai',
    tagline: 'Transforming patient engagement through multilingual voice AI',
    biography:
      "Dr. Mridul Rampal is Co-Founder and Chief Medical Officer at 2care.ai, a Voice AI platform transforming hospital front desks across India with support for Hindi, English, and regional languages. He also leads the company's go-to-market strategy in India, driving hospital partnerships and commercial growth.\nA retired Major from the Indian Army Medical Corps, he brings seven years of clinical experience spanning trauma centres, high-altitude postings, and frontline deployments including Operation Sindoor in J&K, alongside an MBBS.\nHis clinical background shapes 2care.ai's approach to post-discharge care, escalation protocols, and multilingual patient communication as the company deploys AI voice agents across hospitals in India, the UK, and the US.",
    photoUrl: drMridulRampalPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 27,
    expertise: ['Voice AI', 'Patient Engagement', 'Multilingual Healthcare Communication', 'Post-Discharge Care', 'Go-To-Market Strategy'],
    highlights: [
      { label: 'Current', value: 'Co-Founder & Chief Medical Officer, 2care.ai' },
      { label: 'Focus', value: 'GTM strategy in India — hospital partnerships & commercial growth' },
      { label: 'Background', value: 'Retired Major, Indian Army Medical Corps — 7 years clinical experience' },
      { label: 'Deployments', value: 'Trauma centres, high-altitude postings & Operation Sindoor, J&K' },
      { label: 'Reach', value: 'AI voice agents deployed across hospitals in India, the UK & the US' },
    ],
    education: [
      { degree: 'MBBS', institution: '', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-samir-karpe',
    name: 'Samir Karpe',
    title: 'Country Manager, India',
    organization: 'DoubleVerify',
    tagline: 'Driving business growth and digital advertising excellence',
    biography:
      "Samir Karpe serves as Country Manager, India at DoubleVerify, where he leads initiatives focused on driving business growth and ensuring digital advertising excellence. With a rich background in marketing and advertising, Samir brings close to 2 decades of experience in sales strategy, client management, and business development.\nThroughout his career, Samir has consistently demonstrated a deep understanding of the digital landscape, delivering innovative solutions to meet complex business needs. His expertise spans negotiation, management, and fostering strong client relationships to drive success.\nPrior to his role at DoubleVerify, Samir held leadership positions at Viacom18's Voot, where he led sales strategy and agency business. His tenure at Voot saw significant contributions to the platform's growth and success. Before this, Samir spent nearly six years at Radio Mirchi, where he managed key client accounts, enhancing client satisfaction and business outcomes.\nHis leadership style focuses on collaboration, adaptability, and delivering measurable results in a constantly evolving digital environment.",
    photoUrl: samirKarpePhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 28,
    expertise: ['Digital Advertising', 'Sales Strategy', 'Client Management', 'Business Development', 'Negotiation'],
    highlights: [
      { label: 'Current', value: 'Country Manager, India — DoubleVerify' },
      { label: 'Previously', value: "Sales Strategy & Agency Business Lead, Viacom18's Voot" },
      { label: 'Background', value: 'Nearly 6 years managing key client accounts at Radio Mirchi' },
      { label: 'Experience', value: '~20 years in sales strategy, client management & business development' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-bharat-gupta',
    name: 'Bharat Gupta',
    title: 'Founder & Chief Architect',
    organization: 'ToBe',
    tagline: 'Building AI-powered communication governance solutions for regulated industries',
    biography:
      "Bharat Gupta is the Founder & Chief Architect of ToBe, a trust infrastructure company building AI-powered communication governance solutions for regulated industries. With over 25 years of experience at the intersection of digital media, technology, public interest regulation, and platform innovation, Bharat has led organizations through periods of rapid growth and transformation.\nAs the former CEO of Jagran New Media, he scaled one of India's largest digital publishing businesses to over 100 million users. He is a Founding Member and Director of the Digital News Publishers Association (DNPA), served as President of INMA South Asia, and founded India's first Hindi fact-check platform.\nHe is passionate about leveraging AI to strengthen trust, transparency, and accountability across digital ecosystems. At ToBe, Bharat is driving the vision for a new generation of communication governance that enables organizations to build trust through accurate, evidence-backed, and compliant public communication. Bharat is also an active contributor to industry initiatives spanning digital governance, product innovation, and responsible AI.",
    photoUrl: bharatGuptaPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 29,
    expertise: ['Communication Governance', 'AI & Trust Infrastructure', 'Digital Media', 'Public Interest Regulation', 'Platform Innovation'],
    highlights: [
      { label: 'Current', value: 'Founder & Chief Architect, ToBe' },
      { label: 'Previously', value: 'CEO, Jagran New Media — scaled to 100M+ users' },
      { label: 'Leadership', value: 'Founding Member & Director, DNPA · President, INMA South Asia' },
      { label: 'Also Founded', value: "India's first Hindi fact-check platform" },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-ravindra-mk',
    name: 'Ravindra M.K',
    title: 'Entrepreneur & Founding Member',
    organization: 'BHIVE Workspace',
    tagline: 'Building thriving startup ecosystems through community & innovation',
    biography:
      "Ravindra M.K. is a founding member of BHIVE Workspace, one of India's leading coworking and managed workspace providers. Over the years, he has played a key role in building and scaling entrepreneurial communities, helping startups, innovators, and growing businesses access the infrastructure, networks, and ecosystem support needed to thrive.\nWith deep experience in startup ecosystems, business growth, and community building, Ravindra has worked closely with founders across sectors, giving him a unique perspective on how businesses scale, build trust, and create lasting customer relationships. His expertise lies in bringing together people, ideas, and opportunities to foster innovation and sustainable growth.\nAt Allhealth X Tech Summit 2026, Ravindra brings valuable insights on community-led growth, brand building, and how emerging technologies such as AI are reshaping the way organizations engage with customers and markets.",
    photoUrl: ravindraMkPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 30,
    expertise: ['Startup Ecosystems', 'Community-Led Growth', 'Business Scaling', 'Brand Building', 'AI in Customer Engagement'],
    highlights: [
      { label: 'Current', value: 'Founding Member, BHIVE Workspace' },
      { label: 'Focus', value: 'Building and scaling entrepreneurial communities across India' },
      { label: 'Expertise', value: 'Startup ecosystems · Business growth · Community building' },
      { label: 'At the Summit', value: 'Community-led growth, brand building & AI in customer engagement' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-gayathri-vivekanandan',
    name: 'Gayathri Vivekanandan',
    title: 'CEO',
    organization: 'HXAI',
    tagline: 'Driving AI-powered transformation in healthcare',
    biography:
      "Gayathri Vivekanandan is the Chief Executive Officer of HXAI, where she leads the company's vision as an AI Transformation Partner for the US healthcare ecosystem. With over 30 years of experience leading complex technology and digital transformation programs, she has held leadership roles at global organizations including Infosys and HCL, delivering large-scale initiatives across the BFSI, eCommerce, telecommunications, and other industries.\nAt HXAI, Gayathri is driving the adoption of AI through secure, platform-led, outcome-driven transformation, helping healthcare organizations modernize with confidence and deliver measurable impact. A passionate advocate for women in technology, she is equally committed to building high-performing teams and empowering the next generation of technology leaders.",
    photoUrl: gayathriVivekanandanPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 31,
    expertise: ['AI Transformation', 'Healthcare Technology', 'Digital Transformation', 'Platform-Led Strategy', 'Women in Technology', 'Team Leadership'],
    highlights: [
      { label: 'Current', value: 'CEO, HXAI' },
      { label: 'Experience', value: '30+ years leading complex technology & digital transformation programs' },
      { label: 'Background', value: 'Leadership roles at Infosys & HCL across BFSI, eCommerce & telecommunications' },
      { label: 'Focus', value: 'AI Transformation Partner for the US healthcare ecosystem' },
    ],
    education: [],
    awards: [],
  },
  {
    id: 'speaker-dr-ramesh-karmegam',
    name: 'Dr. Ramesh Karmegam',
    title: 'Chief Operating Officer',
    organization: 'Magnet Hospitals',
    tagline: 'Driving innovation in hospital care & healthcare delivery',
    biography:
      "Dr. Ramesh Karmegam is the Chief Operating Officer of Magnet Hospitals, where he leads healthcare delivery across the group's eight hospitals. Magnet Hospitals is built on a unique co-ownership model that empowers doctors and nurses as equity partners, fostering greater clinical accountability, transparency, and patient trust.\nA doctor-entrepreneur with over two decades of leadership experience, Dr. Karmegam's career spans emergency medicine, hospital operations, healthcare strategy, digital health, health insurance, diagnostics, and healthcare innovation.\nDr. Karmegam is the former Founder & CEO of Neo TrueNorth Hospitals, which was acquired by Magnet Hospitals. At Neo TrueNorth, he led the development of India's Emergency-First Smart Hospital model, focused on delivering accessible, affordable, and technology-enabled secondary care. He also served as Project Head for PES University Medical College Hospital, where he led the planning and commissioning of nearly 1.8 million square feet of integrated medical college and hospital infrastructure.\nEarlier, Dr. Karmegam founded WhiteCross Clinic, one of India's pioneering Smart Emergency Care Clinic networks, which expanded to more than 150 clinics across 18 cities and served over one million patients. He also served as Vice President at Medi Assist, where he was responsible for healthcare delivery across a nationwide network of more than 10,000 hospitals and diagnostic centres.\nDr. Karmegam is a physician with a Fellowship in Hospital Management from Canada. He is a recognized healthcare leader and frequent speaker on hospital transformation, healthcare innovation, digital health, emergency care, and scalable healthcare delivery models. His diverse experience across primary and secondary care, hospital development, diagnostics, health insurance, and health technology enables him to bring a unique systems perspective to shaping the future of healthcare.",
    photoUrl: drRameshKarmegamPhoto,
    photoPosition: 'center top',
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: true,
    displayOrder: 32,
    expertise: ['Hospital Operations', 'Emergency Medicine', 'Healthcare Strategy', 'Digital Health', 'Health Insurance', 'Healthcare Innovation'],
    highlights: [
      { label: 'Current', value: 'Chief Operating Officer, Magnet Hospitals' },
      { label: 'Previously', value: 'Founder & CEO, Neo TrueNorth Hospitals (acquired by Magnet Hospitals)' },
      { label: 'Also Founded', value: 'WhiteCross Clinic — 150+ Smart Emergency Care Clinics across 18 cities, 1M+ patients served' },
      { label: 'Background', value: 'Vice President, Medi Assist — healthcare delivery across 10,000+ hospitals & diagnostic centres' },
    ],
    education: [
      { degree: 'Fellowship in Hospital Management', institution: 'Canada', year: '', achievement: '' },
      { degree: 'MBBS', institution: '', year: '', achievement: '' },
    ],
    awards: [],
  },
  {
    id: 'speaker-dr-karan-suresh',
    name: 'Dr. Karan Suresh',
    title: '',
    organization: 'MediBuddy',
    tagline: '',
    biography: '',
    photoUrl: null,
    linkedinUrl: '',
    twitterUrl: '',
    isFeatured: false,
    displayOrder: 33,
    expertise: [],
    highlights: [],
    education: [],
    awards: [],
  },
]

const agendaRecords = [
  {
    id: 'session-registration',
    displayOrder: 1,
    title: 'Registration & Welcome Tea',
    startTime: '2026-07-27T09:45:00+05:30',
    endTime: '2026-07-27T10:30:00+05:30',
    track: null,
    type: 'registration',
    description: 'Arrive early, collect your badge, grab a cup of tea, and start connecting with fellow attendees and ecosystem stakeholders before the sessions begin.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-opening',
    displayOrder: 2,
    title: 'Welcome & Opening Remarks',
    startTime: '2026-07-27T10:35:00+05:30',
    endTime: '2026-07-27T10:40:00+05:30',
    track: null,
    type: 'emcee',
    description: 'Setting the stage for a day focused on healthcare innovation, technology adoption, and the future of care delivery. An overview of the day\'s agenda, session formats, and networking opportunities.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-keynote-1',
    displayOrder: 3,
    title: 'Keynote Address',
    startTime: '2026-07-27T10:50:00+05:30',
    endTime: '2026-07-27T11:05:00+05:30',
    track: 'Keynote',
    type: 'keynote',
    description: 'A look at the trends, opportunities, and evolution of the healthtech ecosystem.',
    speakerId: 'speaker-dr-dario-heymann',
    speakers: [],
  },
  {
    id: 'session-sponsor-1',
    displayOrder: 4,
    title: 'Partner Spotlight',
    partnerLogo: prodocLogo,
    partnerName: 'ProDOC',
    startTime: '2026-07-27T11:10:00+05:30',
    endTime: '2026-07-27T11:30:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare. Presented by Raghuvamshi Thakur.',
    speakerId: 'speaker-raghuvamshi-thakur',
    speakers: [],
  },
  {
    id: 'session-keynote-2',
    displayOrder: 5,
    title: 'Keynote Address',
    startTime: '2026-07-27T11:30:00+05:30',
    endTime: '2026-07-27T11:45:00+05:30',
    track: 'Keynote',
    type: 'keynote',
    description: 'Exploring emerging opportunities at the intersection of healthcare, technology, and innovation.',
    speakerId: 'speaker-dr-uma-nambiar',
    speakers: [],
  },
  {
    id: 'session-panel-1',
    displayOrder: 6,
    title: 'Panel: Hospitals & HealthTech — Building Better Healthcare Together',
    startTime: '2026-07-27T12:00:00+05:30',
    endTime: '2026-07-27T12:25:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'How hospitals and technology companies can work together to improve patient outcomes, operational efficiency, and digital transformation.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-ujjvala-ballal-shetty', name: 'Dr. Ujjvala Shetty' },
      { speakerId: 'speaker-dr-karamveer-chhabra', name: 'Dr. Karamveer' },
      { speakerId: 'speaker-dr-amit-raj', name: 'Dr. Amit Raaj' },
      { speakerId: 'speaker-dr-saarthak-bakshi', name: 'Dr. Sarthak Bakshi' },
    ],
  },
  {
    id: 'session-fireside',
    displayOrder: 7,
    title: 'Fireside Chat',
    startTime: '2026-07-27T12:25:00+05:30',
    endTime: '2026-07-27T12:45:00+05:30',
    track: 'Fireside',
    type: 'fireside',
    description: 'An intimate conversation with the healthcare leader on innovation, adoption, and scaling healthcare solutions.',
    speakerId: 'speaker-dr-bhaskar-rajakumar',
    speakers: [],
  },
  {
    id: 'session-sponsor-2',
    displayOrder: 8,
    title: 'Partner Spotlight',
    partnerLogo: hxaiLogo,
    partnerName: 'HXAI',
    startTime: '2026-07-27T12:45:00+05:30',
    endTime: '2026-07-27T13:05:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare. Presented by Gayathri Vivekanandan.',
    speakerId: 'speaker-gayathri-vivekanandan',
    speakers: [],
  },
  {
    id: 'session-panel-2',
    displayOrder: 9,
    title: 'Panel: Data, Devices & Duty of Care',
    startTime: '2026-07-27T13:08:00+05:30',
    endTime: '2026-07-27T13:35:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'Compliance Considerations for AI-Powered Diagnostics in Clinical Workflows. Moderator: VS Venkatesh.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-vs-venkatesh', name: 'VS Venkatesh', role: 'Moderator' },
      { speakerId: 'speaker-vivek-rajagopal', name: 'Vivek Rajagopal', organization: 'Narayana Health' },
      { speakerId: 'speaker-dr-muthu-dhandapani' },
      { speakerId: 'speaker-dr-anup-warrier', name: 'Anup R Warrier', organization: 'Aster DM Healthcare' },
      { speakerId: 'speaker-dr-vamsi-krishna', name: 'Dr. Vamsi Krishna', organization: 'Apollo Radiology International' },
    ],
  },
  {
    id: 'session-lunch',
    displayOrder: 10,
    title: 'Lunch Break',
    startTime: '2026-07-27T13:35:00+05:30',
    endTime: '2026-07-27T13:55:00+05:30',
    track: null,
    type: 'break',
    description: 'Enjoy lunch connecting with founders, healthcare leaders, investors, clinicians, and innovators.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-sponsor-3',
    displayOrder: 11,
    title: 'Partner Spotlight',
    startTime: '2026-07-27T14:00:00+05:30',
    endTime: '2026-07-27T14:10:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-3',
    displayOrder: 12,
    title: 'Panel: The HealthTech Founder Perspective',
    startTime: '2026-07-27T14:10:00+05:30',
    endTime: '2026-07-27T14:35:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'Building, scaling, and navigating the realities of creating healthcare startups. Moderator: Dr. Karan Suresh.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-dr-karan-suresh', role: 'Moderator' },
      { speakerId: 'speaker-dr-anand-sivaraman', name: 'Anand Sivaraman', organization: 'Remidio' },
      { speakerId: 'speaker-smita-malipatil', name: 'Smita Malipatil', organization: 'Hosa Health' },
      { speakerId: 'speaker-raghuvamshi-thakur' },
      { speakerId: 'speaker-dr-ramesh-karmegam' },
    ],
  },
  {
    id: 'session-pitch',
    displayOrder: 13,
    title: 'The 3-Minute Pitch',
    startTime: '2026-07-27T14:40:00+05:30',
    endTime: '2026-07-27T15:40:00+05:30',
    track: 'Interactive',
    type: 'interactive',
    description: 'Selected startups showcase their innovations before an audience of healthcare leaders, investors, and ecosystem stakeholders.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-panel-4',
    displayOrder: 14,
    title: 'Panel: The VC Perspective — AI, Agents & the Future of Healthcare',
    startTime: '2026-07-27T15:45:00+05:30',
    endTime: '2026-07-27T16:10:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'What investors are looking for in healthcare and healthtech today, and where the next opportunities lie. Moderator: yet to be finalised.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-ashima-setia', name: 'Ashima', organization: 'Sorin Investments' },
      { speakerId: 'speaker-anirudh-iyer', name: 'Anirudh', organization: 'Xeed Ventures' },
      { speakerId: 'speaker-shivani-kulkarni', name: 'Shivani', organization: 'PrimeVP' },
      { speakerId: 'speaker-kamini-shivalkar', name: 'Kamini', organization: 'Gemba Capital' },
    ],
  },
  {
    id: 'session-hi-tea',
    displayOrder: 15,
    title: 'Networking Break — Hi-Tea',
    startTime: '2026-07-27T16:10:00+05:30',
    endTime: '2026-07-27T16:25:00+05:30',
    track: null,
    type: 'break',
    description: 'Refreshments and conversations.',
    speakerId: null,
    speakers: [],
  },
  {
    id: 'session-sponsor-4',
    displayOrder: 16,
    title: 'Partner Spotlight',
    partnerLogo: certinalLogo,
    partnerName: 'Certinal',
    startTime: '2026-07-27T16:35:00+05:30',
    endTime: '2026-07-27T16:50:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare. Presented by Khanjan Kotecha.',
    speakerId: 'speaker-khanjan-kotecha',
    speakers: [],
  },
  {
    id: 'session-panel-5',
    displayOrder: 17,
    title: 'Panel: Regulation, Compliance & the Law',
    startTime: '2026-07-27T17:00:00+05:30',
    endTime: '2026-07-27T17:25:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'Navigating policy, regulation, data governance, and legal considerations in healthcare innovation.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-sneha-bhonsle', name: 'Sneha Bhonsle' },
      { speakerId: 'speaker-khanjan-kotecha', name: 'Khanjan Kotecha', organization: 'Certinal' },
      { speakerId: 'speaker-dr-ajit-audipudi', name: 'Dr. Ajit Audipudi' },
    ],
  },
  {
    id: 'session-sponsor-5',
    displayOrder: 18,
    title: 'Partner Spotlight',
    partnerLogo: tobeLogo,
    partnerName: 'ToBe',
    partnerLogoClass: 'max-h-4',
    startTime: '2026-07-27T17:30:00+05:30',
    endTime: '2026-07-27T17:40:00+05:30',
    track: null,
    type: 'sponsor',
    description: 'Insights from an industry partner driving innovation in healthcare. Presented by Bharat Gupta.',
    speakerId: 'speaker-bharat-gupta',
    speakers: [],
  },
  {
    id: 'session-panel-6',
    displayOrder: 19,
    title: 'Panel: AI in Healthcare Marketing',
    startTime: '2026-07-27T17:45:00+05:30',
    endTime: '2026-07-27T18:10:00+05:30',
    track: 'Panel',
    type: 'panel',
    description: 'How AI is reshaping patient engagement, communication, growth, and healthcare brand building. Moderator: Dr. Mridul Rampal.',
    speakerId: null,
    speakers: [
      { speakerId: 'speaker-dr-mridhul', name: 'Dr. Mridul Rampal', role: 'Moderator' },
      { speakerId: 'speaker-kirti-yadav', name: 'Kriti Yadav' },
      { speakerId: 'speaker-samir-karpe', name: 'Samir Karpe' },
      { speakerId: 'speaker-bharat-gupta', name: 'Bharat Gupta' },
      { speakerId: 'speaker-ravindra-mk' },
    ],
  },
  {
    id: 'session-gala',
    displayOrder: 20,
    title: 'Networking, Booth Exploration & Gala Dinner',
    startTime: '2026-07-27T18:15:00+05:30',
    endTime: '2026-07-27T19:15:00+05:30',
    track: null,
    type: 'gala',
    description: 'Meet exhibitors, discover new solutions, and continue conversations with fellow attendees. Wrap up the day with an evening of great conversations, new connections, and meaningful networking.',
    speakerId: null,
    speakers: [],
  },
]

function sortByDisplayOrder(items) {
  return items.slice().sort((a, b) => a.displayOrder - b.displayOrder)
}

function buildSpeakerMap(speakers) {
  return new Map(speakers.map((speaker) => [speaker.id, speaker]))
}

function attachSpeakersToAgenda(agendaItems, speakerMap) {
  return sortByDisplayOrder(agendaItems).map((item) => ({
    ...item,
    speaker: item.speakerId ? speakerMap.get(item.speakerId) ?? null : null,
    speakers: (item.speakers || []).map((s) => {
      if (!s.speakerId) return s
      const record = speakerMap.get(s.speakerId)
      return record
        ? {
            ...s,
            name: record.name,
            photoUrl: record.photoUrl,
            title: record.title,
            organization: s.organization ?? record.organization,
          }
        : s
    }),
  }))
}

function attachSessionsToSpeakers(speakers, agendaItems) {
  const sessionsBySpeakerId = new Map()
  for (const item of agendaItems) {
    const addSession = (id) => {
      if (!sessionsBySpeakerId.has(id)) sessionsBySpeakerId.set(id, [])
      const list = sessionsBySpeakerId.get(id)
      if (!list.some((i) => i.id === item.id)) list.push(item)
    }
    if (item.speakerId) addSession(item.speakerId)
    for (const s of item.speakers ?? []) {
      if (s.speakerId) addSession(s.speakerId)
    }
  }
  return sortByDisplayOrder(speakers).map((speaker) => ({
    ...speaker,
    sessions: sessionsBySpeakerId.get(speaker.id) ?? [],
  }))
}

export function getEventData() {
  const speakers = sortByDisplayOrder(speakerRecords)
  const speakerMap = buildSpeakerMap(speakers)
  const agendaItems = attachSpeakersToAgenda(agendaRecords, speakerMap)

  return {
    speakers: attachSessionsToSpeakers(speakers, agendaItems),
    agendaItems,
  }
}
